import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import * as runtime from '../compiler-probe/runtime/node_modules/@midnight-ntwrk/compact-runtime/dist/index.js';
import {Contract} from '../kernel-prototype/output/contract/index.js';
const projection=JSON.parse(readFileSync(new URL('../kernel-prototype/projection.json',import.meta.url)));
const msg=Uint8Array.from(Buffer.from(projection.framed.signing_message_hex,'hex'));
const sig={r:BigInt('0x'+projection.artifact.signatureHex.slice(0,64)),s:BigInt('0x'+projection.artifact.signatureHex.slice(64))};
const pk={x:BigInt(projection.publicKey.x),y:BigInt(projection.publicKey.y),identity:false};
const bytes=x=>Uint8Array.from(Buffer.from(x,'hex')),coin='00'.repeat(32),address='04'.repeat(32);
const contract=new Contract({});
const init=await contract.initialState(runtime.createConstructorContext({},coin),pk,bytes('a1'.repeat(32)),{bytes:bytes('02'.repeat(32))},{bytes:bytes('03'.repeat(32))},10000n,10000n,10n,1n);
init.currentContractState.balance=new Map([[{tag:'unshielded',raw:'a1'.repeat(32)},10000n]]);
const context=()=>runtime.createCircuitContext({circuitId:'pay',contractAddress:address,coinPublicKeyOrZswapState:coin,contractState:init.currentContractState,privateState:{},time:1,parentBlockHash:'00'.repeat(32)});
const outcome=await contract.circuits.pay(context(),msg,sig);
assert.equal(outcome.context.callProofDataTrace.length,1);
const trace=outcome.context.callProofDataTrace[0];assert.equal(trace.circuitId,'pay');
const keyLocation='local-public-fixture/pay/c20c6e733500823c478eea885bebab5d62ba9958cfdd1ec8cf2ae89b32f9d7ae';
function serialize(name,input,output,ops,privateOutputs){const encoded=runtime.proofDataIntoSerializedPreimage(input,output,ops,privateOutputs,keyLocation);writeFileSync(new URL(name+'.preimage',import.meta.url),encoded);return {name,bytes:encoded.length,sha256:createHash('sha256').update(encoded).digest('hex')};}
const receipts=[serialize('good',trace.input,trace.output,trace.publicTranscript,trace.privateTranscriptOutputs)];
// Use the official converter on an altered aligned return value, preserving its alignment.
const changedOutput=structuredClone(trace.output);assert.ok(changedOutput.value.length>0);changedOutput.value[0]=changedOutput.value[0].map((v,i)=>i===0?v^1:v);
receipts.push(serialize('forged-output',trace.input,changedOutput,trace.publicTranscript,trace.privateTranscriptOutputs));
const inputFrame=structuredClone(trace.input);inputFrame.value[0][inputFrame.value[0].length-1]^=1;
receipts.push(serialize('forged-frame',inputFrame,trace.output,trace.publicTranscript,trace.privateTranscriptOutputs));
const inputSignature=structuredClone(trace.input);inputSignature.value[1][0]^=1;
receipts.push(serialize('forged-signature',inputSignature,trace.output,trace.publicTranscript,trace.privateTranscriptOutputs));
const wrongHead=structuredClone(trace.publicTranscript),initialHead='9e4601c9af94102208bd6bdea6693cbf5a9638f6d6b9fa716eae540443cc30e4';
const headIndex=wrongHead.findIndex(op=>op.popeq && Buffer.from(op.popeq.result.value[0]).toString('hex')===initialHead);assert.ok(headIndex>=0);wrongHead[headIndex].popeq.result.value[0][0]^=1;
receipts.push(serialize('forged-head-read',trace.input,trace.output,wrongHead,trace.privateTranscriptOutputs));
const wrongEffect=structuredClone(trace.publicTranscript);
const effectIndex=wrongEffect.findIndex(op=>op.popeq && Buffer.from(op.popeq.result.value[0]).toString('hex')==='e803');assert.ok(effectIndex>=0);wrongEffect[effectIndex].popeq.result.value[0][0]^=1;
receipts.push(serialize('forged-recipient-post-read',trace.input,trace.output,wrongEffect,trace.privateTranscriptOutputs));
const frameChanged=msg.slice();frameChanged[frameChanged.length-1]^=1;await assert.rejects(contract.circuits.pay(context(),frameChanged,sig));
await assert.rejects(contract.circuits.pay(context(),msg,{r:sig.r,s:0n}));
const stringify=v=>JSON.stringify(v,(_,x)=>typeof x==='bigint'?{bigint:x.toString()}:x instanceof Uint8Array?{bytes:Buffer.from(x).toString('hex')}:x,2);
writeFileSync(new URL('runtime-proof-data.json',import.meta.url),stringify({input:trace.input,output:trace.output,publicTranscript:trace.publicTranscript,privateTranscriptOutputs:trace.privateTranscriptOutputs}));
writeFileSync(new URL('export-receipt.json',import.meta.url),JSON.stringify({scope:'public local invocation; official native serializer; no native check/proof',keyLocation,bindingInput:'official converter sets zero',communications:'official converter computes transient hash of [0,input values,output values] with randomness zero',receipts,runtimeRejections:['changed production frame','zero signature s'],nativeCheckStatus:'HELD'},null,2));
console.log(JSON.stringify(receipts));
