from pathlib import Path
import json,hashlib
base=Path(__file__).parent
metadata={
'U01':('An Empirical Investigation into Programming Language Syntax',['Andreas Stefik','Susanna Siebert'],'2013','ACM Transactions on Computing Education 13(4), article 19','10.1145/2534973',[6,7,8,9,13,26,27,28,29,30,31,32,33,34,35,36], 'Complete primary paper, third-party public mirror; no publisher-version hash comparison'),
'U02':('PLIERS: A Process that Integrates User-Centered Methods into Programming Language Design',['Michael Coblenz','Gauri Kambhatla','Paulette Koronkevich','Jenna L. Wise','Celeste Barnaby','Joshua Sunshine','Jonathan Aldrich','Brad A. Myers'],'2021','ACM Transactions on Computer-Human Interaction 28(4), article 28','10.1145/3452379',[14,15,16,17,18,19,36,37,38,39,43,44,45,46],'Published author-hosted full paper; its included Obsidian RCT is not separately counted'),
'U04':('Static Type Systems (Sometimes) have a Positive Impact on the Usability of Undocumented Software: An Empirical Evaluation',['Clemens Mayer','Stefan Hanenberg','Romain Robbes','Éric Tanter','Andreas Stefik'],'2012','University of Chile technical report TR_DCC-20120418-005',None,list(range(4,15)),'University technical-report version; final conference-version identity unverified'),
'U05':("On Novices’ Interaction with Compiler Error Messages: A Human Factors Approach",['James Prather','Raymond Pettit','Kayla Holcomb McMurry','Alani Peters','John Homer','Nevan Simone','Maxine Cohen'],'2017','ICER 2017, pp. 74–82','10.1145/3105726.3106169',list(range(6,11)),'Institutional deposited full paper includes cover before article'),
'U06':('Comparing General-Purpose and Domain-Specific Languages: An Empirical Study',['Tomaž Kosar','Nuno Oliveira','Marjan Mernik','Maria João Varanda Pereira','Matej Črepinšek','Daniela da Cruz','Pedro Rangel Henriques'],'2010','Computer Science and Information Systems 7(2), pp. 247–264','10.2298/CSIS1002247K',list(range(15,33)),'Publisher PDF is entire 156-page issue; target article PDF 15–32, printed 247–264'),
'U09':('A Cognitive Dimensions Questionnaire Optimised for Users',['Alan F. Blackwell','Thomas R. G. Green'],'2000','12th Workshop of the Psychology of Programming Interest Group',None,list(range(1,12)),'Proceedings file has 11 physical pages; cover says proceedings pages 137–154; discrepancy retained'),
'U10':('User-Centered Programming Language Design: A Course-Based Case Study',['Michael Coblenz','Ariel Davis','Megan Hofmann','Vivian Huang','Siyue Jin','Max Krieger','Kyle Liang','Brian Wei','Mengchen Sam Yong','Jonathan Aldrich'],'2020-11-15','arXiv:2011.07565v1',None,list(range(1,8)),'Observed title-page v1; fetched unversioned endpoint; exact bytes preserved')}
rows=[]
for id,(title,authors,date,venue,doi,pages,limit) in metadata.items():
 r=json.loads((base/f'{id}.receipt.json').read_text());txt=base/f'{id}.txt'
 rows.append(dict(**r,title=title,authors=authors,publication_date=date,venue=venue,doi=doi,evidence_type='source_fact',source_kind='primary_academic_full_text',inspection='methods_results_limitations_and_relevant_sections',inspected_pdf_pages=pages,extraction_file=str(txt),extraction_sha256=hashlib.sha256(txt.read_bytes()).hexdigest(),coverage_limitation=limit))
failed=[json.loads(p.read_text()) for p in base.glob('*.receipt.json') if p.stem.split('.')[0] not in metadata]
(base/'source-inventory.json').write_text(json.dumps({'schema':'moriarty.language-design.sources.v1','status':'S2-research-only','full_works_count':7,'sources':rows,'unavailable_attempts':failed,'site_pattern_review':'Existing static PDF acquisition pattern sufficient. No cookies, credentials, or new site pattern retained.','capture_notes':['U06 complete issue intentionally retained unchanged','U10 version identified on captured title page']},indent=2,ensure_ascii=False)+'\n')
