import assert from 'node:assert/strict';import {readFileSync,writeFileSync,lstatSync,existsSync} from 'node:fs';import {createHash} from 'node:crypto';import {pathToFileURL} from 'node:url';
const R='/home/charl/Moriarty/.worktrees/sp05-preview-exit',D=R+'/deliverables/sp05-financial-integration-2026-09-09/preview-swap-exit-01';const j=p=>JSON.parse(readFileSync(p)),sha=b=>createHash('sha256').update(b).digest('hex');const {validatePreviewLaunchPlan}=await import(pathToFileURL(R+'/experiments/moriarty-midnight-financial/ledger/preview-launch.mjs'));
// This single original descriptor is public data. Never open its referenced private inputs.
const raw=readFileSync('/home/charl/.local/state/moriarty/sp05-preview-swap-exit-20260910-01/plan.json'),publicRaw=readFileSync(D+'/actual-run/plan.json'),plan=validatePreviewLaunchPlan(JSON.parse(raw)),active=j(D+'/launcher-active.json'),argv=j(D+'/resolved-launch.json').argv,timer=j(D+'/timer-armed.json'),outer=j(D+'/outer-containment-observation-01.json'),cancel=j(D+'/timer-cancellation-01.json');assert.equal(sha(raw),active.planSha256);assert.equal(argv.at(-1),sha(raw));assert.deepEqual(plan,JSON.parse(publicRaw));assert.equal(Buffer.from(JSON.stringify(plan)+'\n').compare(publicRaw),0);assert.equal(plan.limits.deadlineMs,timer.operationDeadlineMs);const draft=j(D+'/public-plan-draft.json');draft.limits.deadlineMs=plan.limits.deadlineMs;assert.deepEqual(draft,plan);
const reservation=j(D+'/actual-run/reservations.json'),result=j(D+'/actual-run/integration-result.json'),native=j(D+'/gpt6-actual-verification-01/gpt6-native-transactions-01.json');assert.equal(reservation.reservedSubmissions,4);assert.equal(reservation.active,null);assert.equal(reservation.reservedDustFee,native.totalNativeDustDebitSpeck);assert(BigInt(reservation.reservedDustFee)<=BigInt(plan.limits.dustFee));assert.deepEqual(reservation.reservedGrossByAsset,result.driver.operationalState.reservedGrossByAsset);assert.equal(reservation.reservedGrossByAsset[result.assetBindings.ASSET_A],plan.limits.grossByLogicalAsset.ASSET_A);assert.equal(reservation.reservedGrossByAsset[result.assetBindings.ASSET_B]??'0',plan.limits.grossByLogicalAsset.ASSET_B);assert.equal(new Set(reservation.identifiers).size,8);assert.deepEqual([...reservation.identifiers].sort(),result.driver.transactionIds.toSorted());
const terminal=j(D+'/terminal-observation-01.json'),stop=j(D+'/explicit-stop-01.json');
const fields=Object.fromEntries(terminal.stdout.trim().split('\n').map(x=>x.split('=')));assert.deepEqual(fields,terminal.observed);
for(const [k,v] of Object.entries({LoadState:'loaded',ActiveState:'active',SubState:'exited',Transient:'yes',Type:'exec',RemainAfterExit:'yes',MainPID:'0',Result:'success',ExecMainCode:'1',ExecMainStatus:'0',InvocationID:active.observed.InvocationID}))assert.equal(fields[k],v);
assert.equal(terminal.startupSha256,sha(readFileSync(D+'/launcher-active.json')));assert.equal(stop.terminalBeforeStopSha256,sha(readFileSync(D+'/terminal-observation-01.json')));assert.equal(stop.returnCode,0);assert.equal(outer.explicitStopSha256,sha(readFileSync(D+'/explicit-stop-01.json')));assert.equal(outer.startupControlGroup,active.observed.ControlGroup);assert.equal(outer.physicalCgroupPath,'/sys/fs/cgroup'+active.observed.ControlGroup);assert.equal(outer.physicalCgroupAbsent,true);assert.equal(outer.containers.length,3);assert(outer.containers.every(c=>c.status==='exited'&&c.pid===0&&c.running===false));assert.equal(outer.timerAtContainment.stdout,'active\n');assert.equal(outer.timerAtContainment.returnCode,0);assert.equal(cancel.returnCode,0);assert.equal(cancel.after.returnCode,0);assert(cancel.after.stdout.includes('ActiveState=inactive'));assert.equal(cancel.precedingContainmentSha256,sha(readFileSync(D+'/outer-containment-observation-01.json')));
const dates=[terminal,stop,outer,cancel].map(x=>Date.parse(x.observedAtUtc));assert(dates.every((x,i)=>!i||x>dates[i-1]));assert(dates[3]<plan.limits.deadlineMs);
const activation=Number(active.observed.ActiveEnterTimestampMonotonic)/1e6;assert(activation>=timer.armingMonotonicSeconds&&activation<timer.setupDeadlineMonotonicSeconds);
assert.equal(result.driver.cleanup.walletStopped,true);assert.equal(result.driver.cleanup.pendingOperations,0);assert.equal(result.driver.cleanup.containmentComplete,false);assert.equal(result.driver.status,'FINANCIAL_COMPLETE');assert.equal(result.status,'FINANCIAL_COMPLETE');assert.equal(result.financialComparison.status,'PASS');assert.equal(result.driver.failure,undefined);
const stdout=j(D+'/stdout-observation-01.json');assert.equal(sha(stdout.line),stdout.lineSha256);assert.deepEqual(JSON.parse(stdout.line),{status:'FINANCIAL_COMPLETE',containmentComplete:false,networkAcceptance:false,proofAcceptance:false,financialAcceptance:false});
const admission=j(D+'/execution-admission.json'),attempt=j(D+'/attempt.json');assert.equal(sha(readFileSync(D+'/execution-admission.json')),attempt.admissionSha256);assert.equal(attempt.status,'CONSUMED');assert.equal(attempt.retryAllowed,false);assert.equal(admission.retryAllowed,false);assert.equal(admission.caseAttempt,2);assert.equal(admission.caseAttemptCap,2);assert.deepEqual(attempt.priorCharges,admission.priorCharges);const charges=admission.priorCharges;
const priorSubs=charges.priorLocalReservedSubmissions+charges.priorPreviewLoanReservedSubmissions+charges.priorPreviewSwapReservedSubmissions+charges.priorPreviewLoanExitReservedSubmissions, priorDust=BigInt(charges.priorLocalReservedDustSpeck)+BigInt(charges.priorPreviewLoanReservedDustSpeck)+BigInt(charges.priorPreviewSwapReservedDustSpeck)+BigInt(charges.priorPreviewLoanExitReservedDustSpeck);assert.equal(priorSubs,23);assert.equal(priorDust,6900000000000023n);assert.equal(priorSubs+reservation.reservedSubmissions,27);assert.equal(priorDust+BigInt(reservation.reservedDustFee),8100000000000027n);
assert(existsSync(plan.wallet.stateDirectory+'/.midnight-wallet-state/preview/.moriarty-backup-sp05-preview-loan-20260910-01'));const paths=[];for(const p of [plan.wallet.stateDirectory,plan.wallet.stateDirectory+'/.midnight-wallet-state/preview',...['shielded','unshielded','dust'].map(k=>plan.wallet.stateDirectory+'/.midnight-wallet-state/preview/'+k+'.json')]){const s=lstatSync(p);assert.equal(s.uid,process.getuid());assert(!s.isSymbolicLink());assert.equal(s.mode&0o777,s.isDirectory()?0o700:0o600);paths.push({path:p,mode:(s.mode&0o777).toString(8),bytes:s.size,metadataOnly:true});}assert(!existsSync(plan.wallet.stateDirectory+'/.midnight-wallet-state/preview/.moriarty-persistence-pending.json'));assert(existsSync(plan.wallet.stateDirectory+'/.midnight-wallet-state/preview/.moriarty-backup-'+plan.limits.allocationId));
writeFileSync(D+'/gpt6-actual-verification-01/accounting.json',JSON.stringify({status:'PASS_SCOPED',publicDescriptorOnlyRead:true,privateSnapshotsOrSecretsRead:false,planSha256:sha(raw),normalizedPlanSha256:sha(publicRaw),exactSourceNormalization:true,activationAfterArmingSeconds:activation-timer.armingMonotonicSeconds,strictExitZeroGate:'PASS_ACTUAL_LOADED_SAME_INVOCATION',exitBeforeExplicitStop:true,outerContainmentObservedBeforeCancellation:true,priorPlusActualReservedSubmissions:priorSubs+reservation.reservedSubmissions,priorPlusActualReservedDustSpeck:(priorDust+BigInt(reservation.reservedDustFee)).toString(),allPriorChargesPreserved:charges,nativeDebitVsIndexerPaidUnits:'unresolved; not equated',snapshotMetadata:paths,privateCapabilityPreimagesOrProvenanceVerified:false},null,2)+'\n');console.log('PASS_SCOPED: exact plan, accounting, metadata and observed strict exit/containment ordering');
