import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import {createHash} from 'node:crypto';import {pathToFileURL} from 'node:url';
const R='/home/charl/Moriarty/.worktrees/sp05-preview-exit',L=R+'/experiments/moriarty-midnight-financial/ledger',D=R+'/deliverables/sp05-financial-integration-2026-09-09/preview-swap-exit-01';const j=p=>JSON.parse(readFileSync(p)),sha=x=>createHash('sha256').update(x).digest('hex');
const {PINNED_NM}=await import(pathToFileURL(L+'/providers.mjs'));const ledger=await import(pathToFileURL(PINNED_NM+'/@midnight-ntwrk/midnight-js-protocol/dist/ledger.mjs'));const {ContractState}=await import(pathToFileURL(PINNED_NM+'/@midnight-ntwrk/midnight-js-protocol/dist/compact-runtime.mjs'));
const {loadProvenFinancialContract}=await import(pathToFileURL(L+'/proven-assets.mjs'));const {extractNativeContractBalances}=await import(pathToFileURL(L+'/contract-balances.mjs'));
const plan=j(D+'/actual-run/plan.json'),build=j(plan.build.receiptPath),loaded=await loadProvenFinancialContract({case:'swap',...plan.build}),states=j(D+'/gpt6-actual-verification-01/gpt6-public-rpc-01/result.json').states,result=j(D+'/actual-run/integration-result.json'),expected=j(L+'/financial-expectations.json').cases.swap;
const publicify=x=>typeof x==='bigint'?x.toString():x instanceof Uint8Array?Buffer.from(x).toString('hex'):Array.isArray(x)?x.map(publicify):x&&typeof x==='object'?Object.fromEntries(Object.entries(x).map(([k,v])=>[k,publicify(v)])):x;
const verified=[];
try{for(const s of states){const raw=Buffer.from(s.serializedStateHex,'hex'),native=ContractState.deserialize(raw);try{assert(Buffer.from(native.serialize()).equals(raw));const decoded=publicify(structuredClone(loaded.decodeState(native.data))),recorded=j(D+'/actual-run/stage-'+s.stage+'.json');assert.deepEqual(decoded,recorded.publicState);const balances=extractNativeContractBalances({state:native});assert.deepEqual(balances,recorded.contractBalances);for(const key of ['kernelState','remaining','revision','initialized'])assert.deepEqual(decoded[key],expected.stages[s.stage][key]);for(const [key,value] of Object.entries(expected.stages[s.stage].lastResults))assert.deepEqual(decoded[key],value);assert.equal(decoded.programDigest,expected.bindingParameters.programDigest);assert.equal(decoded.networkTag,plan.networkTag);assert.equal(decoded.traderAddress.bytes,plan.roles.firstAddress);assert.equal(decoded.providerAddress.bytes,plan.roles.secondAddress);
 const operations=native.operations();assert.deepEqual([...operations].sort(),['close','initialize','swap']);const vks=[];for(const op of operations){const vk=Buffer.from(native.operation(op).verifierKey),artifact=readFileSync(build.assetsPath+'/keys/'+op+'.verifier');assert(vk.equals(artifact));vks.push({operation:op,verifierSha256:sha(vk)});}if(s.stage==='deploy'){const tx=ledger.Transaction.deserialize('signature','proof','binding',readFileSync(D+'/actual-run/public-transactions/'+result.driver.stages[0].transaction.rawSha256+'.bin'));const action=[...tx.intents.values()].flatMap(i=>i.actions)[0];assert.equal(action.address,result.driver.contractAddress);assert(Buffer.from(action.initialState.serialize()).equals(raw));}
 assert(Buffer.from(native.serialize()).equals(raw));verified.push({stage:s.stage,blockHeight:s.blockHeight,stateSha256:sha(raw),nativeBytes:raw.length,allDecodedFieldsEqual:true,allBalancesEqual:true,balances,verifierKeysMatchReviewedBuild:vks});}finally{native.free();}}}finally{loaded.cleanup();}
writeFileSync(D+'/gpt6-actual-verification-01/gpt6-native-historical-states-01.json',JSON.stringify({status:'PASS',scope:'Actual trusted Preview RPC bytes decoded by exact retained compiled swap; all public fields, balances, verifier keys and deployment initial state verified. No new proof or authenticated state proof.',buildReceiptSha256:sha(readFileSync(plan.build.receiptPath)),sourceManifestHash:plan.build.sourceManifestHash,stages:verified},null,2)+'\n');console.log(JSON.stringify({status:'PASS',states:4,buildVerifierKeysMatchedAtEachStage:3,deploymentInitialStateExact:true}));
