import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {pathToFileURL} from 'node:url';
import {captureHistorical,inspectState,ADDRESS,GENESIS} from './probe.mjs';
const ROOT=new URL('../../../../../',import.meta.url),L=new URL('experiments/moriarty-midnight-financial/ledger/',ROOT);
const {loadProvenFinancialContract}=await import(new URL('proven-assets.mjs',L));
const {PINNED_NM}=await import(new URL('providers.mjs',L));const {ContractState}=await import(pathToFileURL(PINNED_NM+'/@midnight-ntwrk/midnight-js-protocol/dist/compact-runtime.mjs'));
const evidence=JSON.parse(readFileSync(new URL('deliverables/sp05-financial-integration-2026-09-09/after-rejection-readback-01/probe-result.json',ROOT)));const hex=evidence.after.serializedStateHex;
const pins=JSON.parse(readFileSync(new URL('./inputs.json',import.meta.url))),plan=JSON.parse(readFileSync(new URL(pins.planPath,ROOT))),build=JSON.parse(readFileSync(plan.build.receiptPath));
const loaded=await loadProvenFinancialContract({case:'loan',...plan.build});test.after(()=>loaded.cleanup());
const cv=x=>typeof x==='bigint'?x.toString():x instanceof Uint8Array?Buffer.from(x).toString('hex'):Array.isArray(x)?x.map(cv):x&&typeof x==='object'?Object.fromEntries(Object.entries(x).map(([k,v])=>[k,cv(v)])):x;
let native=ContractState.deserialize(Buffer.from(hex,'hex'));const state=cv(structuredClone(loaded.decodeState(native.data)));native.free();
const keys=Object.fromEntries(['accrue','initialize','settle'].map(n=>[n,readFileSync(build.assetsPath+'/keys/'+n+'.verifier')]));
const summaries=Object.fromEntries(pins.rows.map(r=>[r.stage,{publicState:state,contractBalances:{}}]));const finalized='0x'+'f'.repeat(64);
function setup(override=()=>undefined){const calls=[];const rpc=async(m,p)=>{calls.push([m,p]);const x=override(m,p,calls.length);if(x!==undefined)return x;if(m==='chain_getFinalizedHead')return finalized;if(m==='chain_getHeader')return {number:'0x5000'};if(m==='chain_getBlockHash')return p[0]===0?GENESIS:p[0]===20480?finalized:pins.rows.find(r=>r.height===p[0]).hash;if(m==='midnight_contractState'){assert.equal(p[0],ADDRESS);assert(pins.rows.some(r=>r.hash===p[1]));return hex;}throw Error('UNEXPECTED');};return {calls,rpc};}
function options(rpc){return {rpc,rows:pins.rows,summaries,loaded,keys,deployInitialHex:hex,deadlineMs:Date.now()+60000};}
test('actual native decoder+reviewed keys through17 bounded controlled RPC calls',async()=>{const {rpc,calls}=setup();const out=await captureHistorical(options(rpc));assert.equal(out.status,'HISTORICAL_STATES_OBSERVED');assert.equal(calls.length,17);assert.equal(out.states.length,4);assert(out.states.every(s=>s.verifierKeys.length===3&&s.allDecodedFieldsEqual));});
test('wrong canonical hash stops before state reads',async()=>{const {rpc,calls}=setup((m,p)=>m==='chain_getBlockHash'&&p[0]===20455?'0x'+'a'.repeat(64):undefined);await assert.rejects(captureHistorical(options(rpc)),/HISTORICAL_CANONICAL/);assert(!calls.some(([m])=>m==='midnight_contractState'));});
test('missing historical method response has no fallback',async()=>{const {rpc,calls}=setup(m=>m==='midnight_contractState'?null:undefined);await assert.rejects(captureHistorical(options(rpc)),/STATE_ENCODING/);assert.equal(calls.filter(([m])=>m==='midnight_contractState').length,1);});
test('complete field mismatch and verifier mismatch reject actual native fixture',()=>{assert.throws(()=>inspectState({hex,row:pins.rows[1],summary:{publicState:{...state,revision:'999'},contractBalances:{}},loaded,keys,deployInitialHex:hex}),/COMPLETE_STATE_MISMATCH/);assert.throws(()=>inspectState({hex,row:pins.rows[1],summary:summaries.initialize,loaded,keys:{...keys,accrue:Buffer.from([0])},deployInitialHex:hex}),/VERIFIER_KEY_MISMATCH/);});
test('late final canonical response cannot report success',async()=>{const real=Date.now;let now=real();Date.now=()=>now;try{const {rpc}=setup((_m,_p,n)=>{if(n===17)now+=60001;});await assert.rejects(captureHistorical(options(rpc)),/QUERY_DEADLINE/);}finally{Date.now=real;}});
