import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const {prepareRepayment:run}=await import(pathToFileURL(`${process.argv[2]}/experiments/moriarty-language/src/successor/repayment.ts`));
const maximum='340282366920938463463374607431768211455';
const record=()=>({schemaVersion:'moriarty-funded-repayment/0',state:{balances:[{party:'Payer',asset:'Token',amount:'200'},{party:'Lender',asset:'Token',amount:'0'}],allowances:[{party:'Payer',asset:'Token',remaining:'200',spent:'0'}],obligations:[{id:'Debt',debtor:'Payer',creditor:'Lender',denomination:'USD',settlementAsset:'Token',principal:'100',accrued:'10',outstanding:'110',allocationRule:'AccrualFirst',conversion:{mantissa:'1',scale:'0',rounding:'none'},status:'Outstanding'}],usedTransferIds:[],usedAllocationIds:[],work:{remaining:'100',spent:'0',closureReserve:'16'}},actions:[{kind:'Transfer',id:'Payment',from:'Payer',to:'Lender',asset:'Token',amount:'7'},{kind:'Repay',allocationId:'Allocation',transferId:'Payment',obligationId:'Debt',payer:'Payer',nominalAmount:'7'}]});
let count=0;const results=[];
function check(name,f){f();count++;results.push(name);}
function good(input){const source=JSON.stringify(input);const before=JSON.stringify(input);const out=run(source);assert.equal(out.status,'Prepared',JSON.stringify(out));assert.equal(JSON.stringify(input),before);assert.equal(out.effects.length,input.actions.length);return out;}
function bad(input){const source=typeof input==='string'?input:JSON.stringify(input);const out=run(source);assert.equal(out.status,'Rejected',JSON.stringify(out));assert.deepEqual(Object.keys(out).sort(),['actionIndex','code','status']);assert.equal(typeof out.code,'string');return out;}
check('SP03 due100 paid30 leaves70 with exactcash/caps/work',()=>{const x=record(),d=x.state.obligations[0];d.accrued='0';d.outstanding='100';x.actions[0].amount='30';x.actions[1].nominalAmount='30';const r=good(x);assert.equal(r.post.obligations[0].outstanding,'70');assert.deepEqual(r.post.balances.map(x=>x.amount),['170','30']);assert.deepEqual(r.post.work,{remaining:'98',spent:'2',closureReserve:'16'});assert.deepEqual(r.post.allowances,[{party:'Payer',asset:'Token',remaining:'170',spent:'30'}]);});
for(const [rule,p,a] of [['AccrualFirst','100','3'],['PrincipalFirst','93','10'],['ProRata','94','9']])check(`policy ${rule}`,()=>{const x=record();x.state.obligations[0].allocationRule=rule;const d=good(x).post.obligations[0];assert.equal(d.principal,p);assert.equal(d.accrued,a);assert.equal(d.outstanding,'103');});
for(const [label,change] of [['missing funding',x=>x.actions.shift()],['future funding',x=>x.actions.reverse()],['wrong payee',x=>x.actions[0].to='Other'],['wrong payer',x=>x.actions[1].payer='Other'],['wrong asset',x=>{x.state.balances[0].asset='Other';x.state.allowances[0].asset='Other';x.actions[0].asset='Other';}],['one token funds seven nominal',x=>x.actions[0].amount='1'],['missing allowance',x=>x.state.allowances=[]],['insufficient allowance',x=>x.state.allowances[0].remaining='6'],['insufficient cash',x=>x.state.balances[0].amount='6'],['closure reserve cannot pay work',x=>x.state.work.remaining='1'],['unknown field',x=>x.state.obligations[0].forgive=true],['fractional amount',x=>x.actions[1].nominalAmount='1.1'],['JSON number',x=>x.actions[1].nominalAmount=7],['zero nominal',x=>x.actions[1].nominalAmount='0'],['zero transfer',x=>x.actions[0].amount='0'],['self transfer',x=>x.actions[0].to='Payer'],['used allocation',x=>x.state.usedAllocationIds=['Allocation']],['used transfer',x=>x.state.usedTransferIds=['Payment']],['overflow credit',x=>x.state.balances[1].amount=maximum],['overflow initialwork',x=>x.state.work.spent=maximum],['inconsistent outstanding',x=>x.state.obligations[0].outstanding='111'],['settled tombstone with live debt',x=>x.state.obligations[0].status='Settled']])check(label,()=>{const x=record();change(x);bad(x);});
check('aggregate funding across different obligations',()=>{const x=record();x.actions[0].amount='30';x.actions[1].nominalAmount='20';x.state.obligations.push({...x.state.obligations[0],id:'Second'});x.actions.push({...x.actions[1],allocationId:'SecondAllocation',obligationId:'Second'});bad(x);x.actions[1].nominalAmount='10';const r=good(x);assert.deepEqual(r.post.obligations.map(d=>d.outstanding),['100','90']);});
check('allocation identity reused for a different debt rejects',()=>{const x=record();x.actions[0].amount='14';x.state.obligations.push({...x.state.obligations[0],id:'Second'});x.actions.push({...x.actions[1],obligationId:'Second'});bad(x);});
check('nominal unit and settlementasset conversion are distinct',()=>{const x=record();x.state.obligations[0].conversion.mantissa='2';x.actions[0].amount='14';const r=good(x);assert.equal(r.effects[1].settlementAmount,'14');assert.equal(r.effects[1].nominalAmount,'7');assert.equal(r.effects[1].denomination,'USD');assert.equal(r.effects[1].settlementAsset,'Token');});
for(const [rounding,cash] of [['floor','10'],['ceil','11']])check(`conversion ${rounding}`,()=>{const x=record();x.state.obligations[0].conversion={mantissa:'15',scale:'1',rounding};x.actions[0].amount=cash;assert.equal(good(x).effects[1].settlementAmount,cash);});
check('non-exact conversion rejects none',()=>{const x=record();x.state.obligations[0].conversion={mantissa:'15',scale:'1',rounding:'none'};x.actions[0].amount='11';bad(x);});
check('rounding cannot discharge with zero settlement',()=>{const x=record();x.state.obligations[0].conversion={mantissa:'1',scale:'1',rounding:'floor'};x.actions[1].nominalAmount='1';bad(x);});
check('refund leaves original gross debit spent',()=>{const x=record();x.state.allowances.push({party:'Lender',asset:'Token',remaining:'7',spent:'0'});x.actions.push({kind:'Transfer',id:'Refund',from:'Lender',to:'Payer',asset:'Token',amount:'7'});const r=good(x);assert.deepEqual(r.post.balances.map(x=>x.amount),['200','0']);assert.equal(r.post.allowances[0].remaining,'193');assert.equal(r.post.allowances[0].spent,'7');});
check('second call carries unpaid obligation and histories',()=>{const first=good(record());const next=record();next.state=first.post;next.actions[0].id='PaymentTwo';next.actions[1].transferId='PaymentTwo';next.actions[1].allocationId='AllocationTwo';const r=good(next);assert.equal(r.post.obligations[0].principal,'96');assert.equal(r.post.obligations[0].accrued,'0');assert.deepEqual(r.post.usedTransferIds,['Payment','PaymentTwo']);assert.equal(r.post.work.remaining,'96');});
check('full repayment retains settled identity',()=>{const x=record();x.actions[0].amount='110';x.actions[1].nominalAmount='110';const r=good(x);assert.equal(r.post.obligations.length,1);assert.equal(r.post.obligations[0].id,'Debt');assert.equal(r.post.obligations[0].status,'Settled');assert.equal(r.post.obligations[0].outstanding,'0');});
check('UInt128 intermediate overflow rejects before division',()=>{const x=record();const p=(1n<<127n).toString();Object.assign(x.state.obligations[0],{principal:p,accrued:'0',outstanding:p,allocationRule:'ProRata'});x.actions[0].amount='2';x.actions[1].nominalAmount='2';bad(x);});
check('capacity must hold after tombstone append',()=>{const x=record();x.state.usedTransferIds=Array.from({length:128},(_,i)=>`Old${i}`);bad(x);});
check('public API never coerces hostile nonstring',()=>{let invoked=false;const r=run({toString(){invoked=true;throw Error('coerced');}});assert.equal(r.status,'Rejected');assert.equal(invoked,false);});
check('duplicate JSON keys rejected before semantics',()=>{const s=JSON.stringify(record()).replace('"schemaVersion":','"schemaVersion":"ignored","schemaVersion":');bad(s);});
check('oversized source rejected',()=>bad(' '.repeat(65537)));
check('deep JSON does not escape structured rejection',()=>bad('['.repeat(10000)+'0'+']'.repeat(10000)));
console.log(JSON.stringify({scope:'Independent funded repayment local projection controls; no authentication/proof/ledger claim',cases:count,pass:true,results},null,2));
