#!/usr/bin/env python3
"""Independent Python check of generated bytes, bounds, source/Core links and IDs."""
from pathlib import Path
import hashlib,json
ROOT=Path(__file__).resolve().parents[4]
HERE=Path(__file__).resolve().parent
SPEC=ROOT/'experiments/moriarty-language/spec'
BOUNDS=json.loads((SPEC/'bounds.json').read_text())
def canonical(x):return json.dumps(x,sort_keys=True,separators=(',',':'),ensure_ascii=False).encode()
def digest(domain,x):return hashlib.sha256(domain.encode()+b'\0'+canonical(x)).hexdigest()
def read(p):
 b=p.read_bytes();v=json.loads(b);assert canonical(v)==b,str(p);return v
def metrics(x):
 m=dict(utf8Bytes=len(canonical(x)),decodedDepthRootZero=0,decodedNodes=0,keysPerRecord=0,arrayLength=0,textUtf8Bytes=0,textJavascriptCodeUnits=0)
 def visit(v,d):
  m['decodedNodes']+=1;m['decodedDepthRootZero']=max(m['decodedDepthRootZero'],d)
  if isinstance(v,str):m['textUtf8Bytes']=max(m['textUtf8Bytes'],len(v.encode()));m['textJavascriptCodeUnits']=max(m['textJavascriptCodeUnits'],len(v.encode('utf-16-le'))//2)
  elif isinstance(v,list):m['arrayLength']=max(m['arrayLength'],len(v));[visit(w,d+1) for w in v]
  elif isinstance(v,dict):m['keysPerRecord']=max(m['keysPerRecord'],len(v));[visit(w,d+1) for w in v.values()]
  else:assert isinstance(v,bool),'forbidden scalar'
 visit(x,0);return m
def lit(v):
 t=v['tag']
 if t=='TextLiteral':return {'tag':'Text','value':v['decoded']}
 if t=='BoolLiteral':return {'tag':'Bool','value':v['value']}
 if t=='AmountLiteral':return {'tag':'Amount','unit':v['unit'],'value':v['token']}
 assert t=='UIntLiteral';return {'tag':'UInt128','value':v['token']}
results=[]
for name in ['loan','swap']:
 d=HERE/'materialized'/name;ast=read(d/'source-ast.json');typed=read(d/'typed-program.json');bound=read(d/'bound-program.json');manifest=read(d/'semantic-manifest.json');source=(SPEC/f'examples/{name}.moriarty').read_bytes();sh=hashlib.sha256(source).hexdigest()
 assert ast['sourceHash']==manifest['sourceHash']==sh
 assert ast['sourceUtf8Bytes']==str(len(source)) and typed['source']==ast and bound['manifest']==manifest
 assert manifest['bounds']['boundsHash']==hashlib.sha256(b'MORIARTY-BOUNDS-bounded-atomic/1\0'+(SPEC/'bounds.json').read_bytes()).hexdigest()
 assert bound['programHash']==digest('MORIARTY-PROGRAM-bounded-atomic/1',manifest)
 checked={}
 for label,obj,limit in [('sourceAST',ast,'astEncoding'),('typedProgram',typed,'typedProgramEncoding'),('boundProgram',bound,'programManifestEncoding')]:
  ms=metrics(obj);assert all(v<=BOUNDS[limit][k] for k,v in ms.items()),(name,label,ms);checked[label]=ms
 for tag,key in [('StateDecl','initialState'),('ConstDecl','constants')]:assert manifest[key]==[{'name':x['name'],'value':lit(x['value'])} for x in ast['declarations'] if x['tag']==tag]
 assert manifest['lifetime']==ast['lifetime']['token'] and manifest['horizon']==ast['horizon']['token']
 actions=[x for x in ast['declarations'] if x['tag']=='ActionDecl'];assert len(actions)==len(manifest['core']['actions']);seen=[];annotations={x['nodeId']:x for x in typed['annotations']};assert len(annotations)==len(typed['annotations'])
 def ref(span):
  assert 0<=int(span['startByte'])<=int(span['endByte'])<=len(source)
  return {'generatedTag':'Source','sourceHash':sh,'spans':[span]}
 for ai,(a,c) in enumerate(zip(actions,manifest['core']['actions'])):
  assert a['name']==c['name'] and c['sourceRef']==ref(a['span']) and len(a['statements'])==len(c['instructions'])
  for si,(s,i) in enumerate(zip(a['statements'],c['instructions'])):
   assert i['statementId']==f'a_{ai}_s_{si}' and i['tag']==s['tag'] and i['sourceRef']==ref(s['span']);counter=[0]
   def expression(e,n):
    node=f'a_{ai}_s_{si}_e_{counter[0]}';counter[0]+=1;seen.append(node)
    assert n['tag']==e['tag'] and n['nodeId']==node and n['sourceRef']==ref(e['span'])
    annotation=annotations[node];assert annotation['sourceRef']==n['sourceRef'] and annotation['type']==n['type'] and annotation['unitVector']==n['unitVector']
    if n['type']['tag'] in ['Bool','Text','UInt128']:assert n['unitVector']==[]
    elif n['type']['tag']=='Amount':assert n['unitVector']==[{'exponent':'1','unit':n['type']['unit']}]
    else:assert n['type']['tag']=='Quantity' and n['type']['unitVector']==n['unitVector']
    t=e['tag']
    if t=='Literal':assert n['value']==lit(e['literal'])
    elif t in ['StateRef','ArgRef','ObservationRef','ConstRef']:assert n['declaration']==e['name']
    elif t=='LocalRef':assert n['local']==e['name'] and n['action']==a['name']
    elif t=='Not':expression(e['operand'],n['operand'])
    elif t=='FloorDiv':expression(e['numerator'],n['numerator']);expression(e['denominator'],n['denominator'])
    elif 'left' in e:expression(e['left'],n['left']);expression(e['right'],n['right'])
    else:assert t=='Remaining'
   if s['tag']=='Guard':expression(s['condition'],i['condition'])
   elif s['tag'] in ['Let','Set']:expression(s['expression'],i['expression'])
   else:
    assert len(s['fields'])==len(i['fields'])
    for sf,cf in zip(s['fields'],i['fields']):assert sf['label']==cf['label'];expression(sf['expression'],cf['expression'])
 assert seen==[x['nodeId'] for x in typed['annotations']]
 results.append({'program':name,'programHash':bound['programHash'],'linkedExpressions':len(seen),'metrics':checked})
print(json.dumps({'status':'pass','scope':'Independent canonical/hash/bounds and exact source-to-Core structural checks; not full typing/evaluation/proof correspondence','results':results},indent=2))
