import assert from 'node:assert/strict';import {readFileSync}from'node:fs';import{pathToFileURL}from'node:url';
const pkg=process.argv[2]+'/experiments/moriarty-language';const {createFinancialExpressionContractV2:v2}=await import(pathToFileURL(pkg+'/src/successor/financial-expression-v2.ts'));const {createFinancialExpressionContractV1:v1}=await import(pathToFileURL(pkg+'/src/successor/financial-expression-v1.ts'));const {canonical:C}=await import(pathToFileURL(pkg+'/src/successor/expression-wire-v1.ts'));
const S={units:['Cash'],assets:['Cash'],vaults:[],parties:[],recordTypes:{},enumTypes:{},variantTypes:{},fields:{},args:{},observations:{},operations:{}};const state=readFileSync(pkg+'/spec/successor/examples/expression-funded-payment.state.json','utf8');const span={kind:'synthetic',start:'0',end:'0'};const N=(constructor,operands)=>({constructor,operands,span});const T=value=>N('LitText',{value});const req=(core,version=2,work='2')=>C({contract:'moriarty-financial-expression-contract/'+version,source:'',core,Pre:{},Args:{},Obs:{},workInitial:work});const cases=[];const check=(name,fn)=>{fn();cases.push(name);};
for(const [tag,key,id,value,type]of[['ReadOutstanding','unit','Due100','100',['Quantity',[['Cash','1']],'0']],['ReadPrincipal','unit','Due100','100',['Quantity',[['Cash','1']],'0']],['ReadAccrued','unit','Due100','0',['Quantity',[['Cash','1']],'0']],['ReadBalance','asset','Payer','100',['Amount','Cash']],['ReadAllowanceRemaining','asset','Payer','100',['Amount','Cash']],['ReadAllowanceSpent','asset','Payer','0',['Amount','Cash']]]){
 const node=N(tag,{[key]:'Cash',identity:T(id)});check(tag+' exact type/value/work',()=>{assert.deepEqual(v2(C(S),state).evaluate(req(node)),{judgmentResult:'ExpressionValue',type,value,workRemaining:'0'});});check(tag+' pure static without context',()=>assert.deepEqual(v2(C(S)).check(req(node)),{judgmentResult:'ExpressionChecked'}));check(tag+' rejected by old Core',()=>assert.equal(v1(C(S)).check(req(node,1)).code,'TYPE_CONSTRUCTOR'));check(tag+' old dead branch remains closed',()=>{const lit=key==='unit'?N('LitQuantity',{units:[['Cash','1']],scale:'0',mantissa:'0'}):N('LitAmount',{asset:'Cash',value:'0'});const select=N('Select',{condition:N('LitBool',{value:false}),consequent:node,alternative:lit});assert.equal(v1(C(S)).check(req(select,1)).code,'TYPE_CONSTRUCTOR');});check(tag+' closed operand shape',()=>{assert.equal(v2(C(S)).check(req(N(tag,{...node.operands,extra:'x'}))).code,'INPUT_SCHEMA');});
}
const read=N('ReadOutstanding',{unit:'Cash',identity:T('Due100')});check('unbound evaluation has no financial authority',()=>assert.equal(v2(C(S)).evaluate(req(read)).code,'FINANCIAL_CONTEXT_REQUIRED'));check('state cannot be injected through request',()=>{const r=JSON.parse(req(read));r.financialPre=JSON.parse(state);assert.equal(v2(C(S)).evaluate(C(r)).code,'INPUT_SCHEMA');});check('bound context is an immutable string snapshot',()=>{const obj=JSON.parse(state),api=v2(C(S),JSON.stringify(obj));obj.obligations[0].outstanding='1';assert.equal(api.evaluate(req(read)).value,'100');});check('nonstring context has no coercion',()=>{let touched=false;const hostile=Object.create(null,{toString:{get(){touched=true;throw Error('coercion');}}});assert.equal(v2(C(S),hostile).evaluate(req(read)).code,'INPUT_SCHEMA');assert.equal(touched,false);});check('state validation cannot be skipped by pure branch',()=>{const bad=JSON.parse(state);bad.obligations.push({...bad.obligations[0]});const core=N('Select',{condition:N('LitBool',{value:false}),consequent:read,alternative:N('LitQuantity',{units:[['Cash','1']],scale:'0',mantissa:'0'})});assert.equal(v2(C(S),JSON.stringify(bad)).evaluate(req(core,2,'3')).code,'DUPLICATE');});check('bound result objects cannot alter later execution',()=>{const api=v2(C(S),state),x=api.evaluate(req(read));x.type.push('wrong');x.value='1';assert.equal(api.evaluate(req(read)).value,'100');});
check('Core admission failure matches its declared expression rejection type',()=>assert.deepEqual(v2(C(S),'{}').evaluate(req(read)),{status:'Rejected',code:'SCHEMA',span,nodePath:[],workUsed:'0'}));
console.log(JSON.stringify({passed:cases.length,cases},null,2));
