import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {readbackAfterRejection,validateEvidence,serializePublicResult} from './probe.mjs';
const json=p=>JSON.parse(readFileSync(new URL(p,import.meta.url))),old=json('../local-stale-loan-01/public-preflight-result.json'),prior=json('../local-finalized-state-02/probe-result.json'),known=prior.snapshots[0],barrier='0x'+'ab'.repeat(32),after='0x'+'cd'.repeat(32),genesis='0xe72f7a21a0397844563b4206f887b779ffa0d937c2d1b2339441faa1f08b9846';
const evidence=()=>({preflight:structuredClone(old),prior:structuredClone(prior),candidate:json('../local-stale-loan-01/run-public/adverse-candidate.json'),candidateRaw:readFileSync(new URL('../local-stale-loan-01/run-public/adverse-candidate.bin',import.meta.url)),outcome:json('../local-stale-loan-01/run-public/adverse-submission-outcome.json'),containment:json('../local-stale-loan-01/terminal-containment.json')});
function transport(change=()=>undefined){let heads=0;const calls=[];return {calls,fetchImpl:async(url,options)=>{assert.equal(url,'http://127.0.0.1:19944/');const b=JSON.parse(options.body);calls.push(b);const custom=change(b,calls);if(custom!==undefined)return custom;let result;
 if(b.method==='chain_getFinalizedHead'){heads++;result=heads<=2?barrier:after;}
 else if(b.method==='chain_getHeader'){result={number:'0x'+(b.params[0]===old.current.blockHash?20422:b.params[0]===barrier?20430:20431).toString(16)};}
 else if(b.method==='chain_getBlockHash')result=b.params[0]===0?genesis:b.params[0]===20422?old.current.blockHash:b.params[0]===20430?barrier:after;
 else if(b.method==='midnight_contractState'){assert.equal(b.params[0],known.contractAddress);assert.ok([old.current.blockHash,after].includes(b.params[1]));result=known.serializedStateHex;}
 else throw Error('UNEXPECTED_RPC');return Response.json({jsonrpc:'2.0',id:b.id,result});}};}
test('actual RPC/native reader/retained generated decoder compare all state after post-terminal barrier',async t=>{t.mock.method(globalThis,'fetch',()=>{throw Error('LIVE_FETCH_FORBIDDEN');});const f=transport(),out=await readbackAfterRejection({fetchImpl:f.fetchImpl,deadlineMs:Date.now()+10000});assert.equal(out.status,'NONMUTATION_OBSERVED',JSON.stringify(out.failure));assert.equal(out.before.blockHeight,20422);assert.equal(out.barrier.blockHeight,20430);assert.equal(out.after.blockHeight,20431);assert.ok(Object.values(out.comparison).every(Boolean));assert.equal(out.loadersClosed,1);assert.equal(f.calls.filter(c=>c.method==='midnight_contractState').length,2);assert.ok(f.calls.every(c=>!c.method.includes('submit')));assert.ok(Buffer.byteLength(serializePublicResult(out))<=65536);});
test('retained candidate/outcome/before/native/terminal mutations reject before network',()=>{for(const mutate of [e=>e.candidateRaw[0]^=1,e=>e.outcome.rpcCode=1011,e=>e.outcome.candidateRawSha256='00'.repeat(32),e=>e.outcome.stalePredicateEstablished=true,e=>e.preflight.current.blockHeight++,e=>e.prior.snapshots[0].serializedStateHex='00',e=>e.containment.units[0].properties.MainPID='1',e=>e.containment.observedAt='2999-01-01T00:00:00Z']){const e=evidence();mutate(e);assert.throws(()=>validateEvidence(e));}});
test('wrong genesis stops with zero state calls',async()=>{const f=transport(b=>b.method==='chain_getBlockHash'&&b.params[0]===0?Response.json({jsonrpc:'2.0',id:b.id,result:'0x'+'00'.repeat(32)}):undefined);const out=await readbackAfterRejection({fetchImpl:f.fetchImpl,deadlineMs:Date.now()+10000});assert.equal(out.failure.code,'GENESIS_MISMATCH');assert.equal(f.calls.filter(c=>c.method==='midnight_contractState').length,0);});
test('noncanonical original BEFORE anchor refuses recovered comparison',async()=>{const f=transport(b=>b.method==='chain_getBlockHash'&&b.params[0]===20422?Response.json({jsonrpc:'2.0',id:b.id,result:barrier}):undefined);const out=await readbackAfterRejection({fetchImpl:f.fetchImpl,deadlineMs:Date.now()+10000});assert.equal(out.status,'UNKNOWN');assert.equal(out.failure.code,'FINALIZED_STATE_NONCANONICAL');assert.equal(out.loadersClosed,1);});
test('actual native state difference after barrier never establishes nonmutation',async()=>{const changed=readFileSync(new URL('../local-recovery-03/indexed-initialize-state.bin',import.meta.url)).toString('hex');const f=transport(b=>b.method==='midnight_contractState'&&b.params[1]===after?Response.json({jsonrpc:'2.0',id:b.id,result:changed}):undefined);const out=await readbackAfterRejection({fetchImpl:f.fetchImpl,deadlineMs:Date.now()+10000});assert.equal(out.status,'UNKNOWN');assert.equal(out.failure.code,'FINANCIAL_NONMUTATION_FAILED');assert.equal(out.comparison.allNativeBytesEqual,false);assert.equal(out.comparison.allDecodedFieldsEqual,false);});
test('unsupported state RPC is UNKNOWN and never retried',async()=>{const f=transport(b=>b.method==='midnight_contractState'?Response.json({jsonrpc:'2.0',id:b.id,error:{code:-32601,message:'missing'}}):undefined);const out=await readbackAfterRejection({fetchImpl:f.fetchImpl,deadlineMs:Date.now()+10000});assert.equal(out.status,'UNKNOWN');assert.equal(f.calls.filter(c=>c.method==='midnight_contractState').length,1);});
test('late same-height barrier yields UNKNOWN under the shared deadline',async t=>{const started=Date.now();let now=started;t.mock.method(Date,'now',()=>now);const f=transport((b,calls)=>{if(b.method==='chain_getFinalizedHead'&&calls.filter(c=>c.method==='chain_getFinalizedHead').length===3){now=started+10001;return Response.json({jsonrpc:'2.0',id:b.id,result:barrier});}});const out=await readbackAfterRejection({fetchImpl:f.fetchImpl,deadlineMs:started+10000});assert.equal(out.status,'UNKNOWN');assert.equal(out.failure.code,'RPC_DEADLINE');assert.equal(out.loadersClosed,1);});
test('head regression during AFTER capture fails the strict post-terminal barrier',async()=>{const f=transport((b,calls)=>{if(b.method==='chain_getFinalizedHead'&&calls.filter(c=>c.method==='chain_getFinalizedHead').length===4)return Response.json({jsonrpc:'2.0',id:b.id,result:barrier});if(b.method==='midnight_contractState'&&b.params[1]===barrier)return Response.json({jsonrpc:'2.0',id:b.id,result:known.serializedStateHex});});const out=await readbackAfterRejection({fetchImpl:f.fetchImpl,deadlineMs:Date.now()+10000});assert.equal(out.status,'UNKNOWN');assert.equal(out.failure.code,'AFTER_NOT_STRICTLY_LATER');});
test('different native bytes at exact canonical BEFORE anchor fail retained-state binding',async()=>{const changed=readFileSync(new URL('../local-recovery-03/indexed-initialize-state.bin',import.meta.url)).toString('hex');const f=transport(b=>b.method==='midnight_contractState'&&b.params[1]===old.current.blockHash?Response.json({jsonrpc:'2.0',id:b.id,result:changed}):undefined);const out=await readbackAfterRejection({fetchImpl:f.fetchImpl,deadlineMs:Date.now()+10000});assert.equal(out.status,'UNKNOWN');assert.equal(out.failure.code,'BEFORE_NATIVE_MISMATCH');assert.equal(f.calls.filter(c=>c.method==='midnight_contractState').length,1);});
test('barrier reorg detected after successful native snapshots prevents equality acceptance',async()=>{const f=transport((b,calls)=>b.method==='chain_getBlockHash'&&b.params[0]===20430&&calls.filter(c=>c.method==='chain_getBlockHash'&&c.params[0]===20430).length===2?Response.json({jsonrpc:'2.0',id:b.id,result:after}):undefined);const out=await readbackAfterRejection({fetchImpl:f.fetchImpl,deadlineMs:Date.now()+10000});assert.equal(out.status,'UNKNOWN');assert.equal(out.failure.code,'ANCHOR_REORG');assert.equal(out.loadersClosed,1);});

test('cleanup crossing deadline cannot return successful nonmutation',async t=>{const started=Date.now();let now=started;t.mock.method(Date,'now',()=>now);const {loadProvenFinancialContract}=await import('../../../experiments/moriarty-midnight-financial/ledger/proven-assets.mjs');const f=transport();const out=await readbackAfterRejection({fetchImpl:f.fetchImpl,deadlineMs:started+10000,loadContract:async options=>{const real=await loadProvenFinancialContract(options);return {...real,cleanup(){const result=real.cleanup();now=started+10001;return result;}};}});assert.equal(out.status,'UNKNOWN');assert.equal(out.failure.code,'READBACK_DEADLINE');assert.equal(out.loadersClosed,1);});
