[package]
name = "mori-checker"
version = "0.1.0"
description = "Name, value and rule checking for Moriarty source"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
mori-ast.workspace = true
mori-diagnostics.workspace = true
mori-lexer.workspace = true
mori-span.workspace = true
soa-rs.workspace = true

[dev-dependencies]
indoc.workspace = true
insta.workspace = true
mori-diagnostics = { workspace = true, features = ["fancy"] }
mori-parser.workspace = true
proptest.workspace = true
