[package]
name = "mori-lexer"
version = "0.1.0"
description = "Lexer for Moriarty source"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
mori-diagnostics.workspace = true
mori-span.workspace = true
soa-rs.workspace = true

[dev-dependencies]
indoc.workspace = true
insta.workspace = true
mori-diagnostics = { workspace = true, features = ["fancy"] }
proptest.workspace = true
