type Equal<A,B>=(<T>()=>T extends A?1:2) extends (<T>()=>T extends B?1:2)?true:false;
type Assert<T extends true>=T;
import type {FundedExpressionPrepared as B0} from "/home/charl/Moriarty/.worktrees/financial-postconditions/experiments/moriarty-language/src/successor/funded-expression-source-v1.ts";
import type {FundedExpressionPrepared as C0} from "/home/charl/Moriarty/.worktrees/loan-origination-accrual/experiments/moriarty-language/src/successor/funded-expression-source-v1.ts";
type Check0=Assert<Equal<B0,C0>>;
import type {FundedExpressionResult as B1} from "/home/charl/Moriarty/.worktrees/financial-postconditions/experiments/moriarty-language/src/successor/funded-expression-source-v1.ts";
import type {FundedExpressionResult as C1} from "/home/charl/Moriarty/.worktrees/loan-origination-accrual/experiments/moriarty-language/src/successor/funded-expression-source-v1.ts";
type Check1=Assert<Equal<B1,C1>>;
import type {createFundedFinancialExpressionSourceV1 as B2} from "/home/charl/Moriarty/.worktrees/financial-postconditions/experiments/moriarty-language/src/successor/funded-expression-source-v1.ts";
import type {createFundedFinancialExpressionSourceV1 as C2} from "/home/charl/Moriarty/.worktrees/loan-origination-accrual/experiments/moriarty-language/src/successor/funded-expression-source-v1.ts";
type Check2=Assert<Equal<typeof B2,typeof C2>>;
import type {createFinancialExpressionContractV1 as B3} from "/home/charl/Moriarty/.worktrees/financial-postconditions/experiments/moriarty-language/src/successor/financial-expression-v1.ts";
import type {createFinancialExpressionContractV1 as C3} from "/home/charl/Moriarty/.worktrees/loan-origination-accrual/experiments/moriarty-language/src/successor/financial-expression-v1.ts";
type Check3=Assert<Equal<typeof B3,typeof C3>>;
import type {createFinancialExpressionContractV2 as B4} from "/home/charl/Moriarty/.worktrees/financial-postconditions/experiments/moriarty-language/src/successor/financial-expression-v1.ts";
import type {createFinancialExpressionContractV2 as C4} from "/home/charl/Moriarty/.worktrees/loan-origination-accrual/experiments/moriarty-language/src/successor/financial-expression-v1.ts";
type Check4=Assert<Equal<typeof B4,typeof C4>>;
import type {createFinancialExpressionContractV3 as B5} from "/home/charl/Moriarty/.worktrees/financial-postconditions/experiments/moriarty-language/src/successor/financial-expression-v1.ts";
import type {createFinancialExpressionContractV3 as C5} from "/home/charl/Moriarty/.worktrees/loan-origination-accrual/experiments/moriarty-language/src/successor/financial-expression-v1.ts";
type Check5=Assert<Equal<typeof B5,typeof C5>>;
import type {createFinancialAgreementSourceV1 as B6} from "/home/charl/Moriarty/.worktrees/financial-postconditions/experiments/moriarty-language/src/successor/financial-agreement-source-v1.ts";
import type {createFinancialAgreementSourceV1 as C6} from "/home/charl/Moriarty/.worktrees/loan-origination-accrual/experiments/moriarty-language/src/successor/financial-agreement-source-v1.ts";
type Check6=Assert<Equal<typeof B6,typeof C6>>;
import type {createFinancialAgreementSourceV2 as B7} from "/home/charl/Moriarty/.worktrees/financial-postconditions/experiments/moriarty-language/src/successor/financial-agreement-source-v2.ts";
import type {createFinancialAgreementSourceV2 as C7} from "/home/charl/Moriarty/.worktrees/loan-origination-accrual/experiments/moriarty-language/src/successor/financial-agreement-source-v2.ts";
type Check7=Assert<Equal<typeof B7,typeof C7>>;
import type {createFinancialAgreementSourceV3 as B8} from "/home/charl/Moriarty/.worktrees/financial-postconditions/experiments/moriarty-language/src/successor/financial-agreement-source-v3.ts";
import type {createFinancialAgreementSourceV3 as C8} from "/home/charl/Moriarty/.worktrees/loan-origination-accrual/experiments/moriarty-language/src/successor/financial-agreement-source-v3.ts";
type Check8=Assert<Equal<typeof B8,typeof C8>>;
import type {createFinancialAgreementSourceV4 as B9} from "/home/charl/Moriarty/.worktrees/financial-postconditions/experiments/moriarty-language/src/successor/financial-agreement-source-v4.ts";
import type {createFinancialAgreementSourceV4 as C9} from "/home/charl/Moriarty/.worktrees/loan-origination-accrual/experiments/moriarty-language/src/successor/financial-agreement-source-v4.ts";
type Check9=Assert<Equal<typeof B9,typeof C9>>;
