from pathlib import Path
import json
r=Path(__file__).parent;c=Path('/home/charl/research/moriarty-consolidation-2026-09-19/candidate');p=c/'docs/MORIARTY-BACKEND-REQUIREMENTS.md'
rows=[
('MNR01','Transcript and challenge specification','ZR01/03/06','The qualified backend SHALL specify canonical transcript absorption order, domain tags, encodings, cross-field/limb conversion and challenge derivation, including verifier identity and recursive messages; circuit and native verifiers SHALL implement that same contract.','Compatible vectors agree; changed index digest, omitted challenge commitment, ambiguous encoding, invalid limbs and semantically changed parent ordering reject.','Pickles/Kimchi M05/M06; E10/E11/E15.','U1/U4'),
('MNR02','Deferred obligations, base cases and active masks','ZR04/07/08/09/16','The interface SHALL identify each deferred obligation, authenticated inputs, producer, consumer and connecting invariant; final acceptance SHALL discharge every active obligation. Branch choice, predecessor cardinality, padding and base-case masks SHALL be constrained by the authorized relation.','Valid base and two-parent continuation pass. Changed deferred scalar/sponge, disabled required finalizer, empty required batch, recursive case relabeled base and dummy promoted to parent reject.','M01–M04/M07; E01–E09/E16; developer D01/D10.','U1/U4'),
('MNR03','Heterogeneous compatibility and key authorization','ZR01/02/05/09/12/13/15','Each side-loaded relation SHALL bind statement schema, field order/encoding, child recursive shape, supported features, domains/chunks/rounds, key and parameter identity. Key data-to-identity integrity and identity-to-owner/program authorization SHALL both hold.','Compatible authorized heterogeneous relations pass; same-shaped trivial relation, misleading key hash, unauthorized key-root update, incompatible feature/field count and oversized domain reject. Distinguish child shape, direct fan-in and total ancestry.','M03/M06; developer D03–D05.','U0/U1/U4'),
('MNR04','Verified values and auxiliary output','ZR03/07/10/11/16','Tooling SHALL distinguish parsed proof data, cryptographically verified statements, witness-only or auxiliary values, predicted effects and authenticated actual effects. Every mandatory effect/history dependency SHALL be constrained and verified; current-state settlement SHALL include authoritative preconditions.','Invalid predecessor with consistent public fields, omitted verify call, altered auxiliary fee/recipient and valid stale-state proof cannot authorize effects. A verified permitted successor bound to current state passes.','Developer D01/D02/D06/D09/D10.','U2/U4'),
('MNR05','Production proof-mode separation','ZR01/07/16','Evidence collection and deployed acceptance SHALL assert real proving and complete verification configuration; simulation, dummy proofs, disabled-proof mode and empty test keys SHALL be visibly distinct and SHALL NOT qualify production acceptance.','A local test-mode success with dummy proof fails an independent real verifier; mode toggles and mock ledger paths cannot yield a final-valid evidence record.','Developer D07; historical Midnight build-mode observations.','U1/U2/U4/U7'),
('MNR06','Parameter and cache provenance','ZR01/05/08/15/16','Cache and parameter artifacts SHALL bind content digests, semantic/build tuple, purpose and expected identity. Batch parameters SHALL have a common authenticated identity or a proved compatibility relation; equal dimensions alone SHALL NOT establish compatibility.','Cold/warm builds preserve qualified semantics; stale/corrupt/relabeled cache entries reject or safely rebuild. Equal-length incompatible parameters reject or use an explicitly sound separate verification path.','M07; developer D08; no exploit claim from inspected TODO.','U1/U4/U7'),
('MNR07','Batching and join soundness','ZR08/09/12/13','Batching SHALL specify coefficient/challenge generation, full-batch binding, randomness assumptions, required cardinality and composed soundness error. Any bounded-fan-in tree decomposition SHALL preserve authorized parent coverage, duties and budgets.','A batch with one invalid member fails under its stated security guarantee; empty required batches, omitted member and adversarial cancellation/coefficient attempts fail. Binary-tree and permitted direct joins preserve the same financial relation; harmless shared ancestry is not duplicated spending.','M07/M08; developer D05. Tests do not replace probabilistic soundness arguments.','U1/U4'),
('MNR08','Specification and component assurance coverage','ZR01/06/14/16','The qualification dossier SHALL trace mathematical statement, specification, compiler constraint and final verifier code for every used feature, and record exact audit/theorem scope and gaps for dependencies, custom gates, lookups, bindings and recursion.','A historical recursion-layer audit cannot qualify an unaudited gate or changed tuple. A complete supported-feature matrix names evidence or an open obligation for every component; documentation/code disagreement remains unresolved until reconciled.','2023 Pickles audit physical pp3/5/6/7/8; present study is not a new audit.','U0/U1/U4/U7'),
]
add='''\n## Mina-derived mandatory refinements\n\nThe [Mina case study](../deliverables/mina-recursion-study-2026-09-19/RESULT.md) adds eight required refinements to ZR01–ZR16. These are detailed acceptance clauses within the same backend contract, not a separate roadmap or a request to port Mina cryptography. All remain specified-only for Midnight. Source codes M/E refer to the [recursion report](../deliverables/mina-recursion-study-2026-09-19/recursion-semantics.md); D refers to the [developer report](../deliverables/mina-recursion-study-2026-09-19/developer-integration.md).\n\n| ID | Requirement | Refines | Positive and hostile evidence | Source basis |\n|---|---|---|---|---|\n'''
for id,title,zr,rule,test,ev,u in rows:add+=f'| {id} — {title} | {rule} | {zr} | {test} | {ev} |\n'
add+='''\nMina's Pickles/IPA/Pasta architecture and Midnight's native PLONK/KZG interfaces have different cryptographic assumptions and artifact formats. Reuse the requirements and failure cases, not claims of interchangeable proofs or automatic theorem transfer. The acquired Mina gitlink matches the separately acquired proof-systems commit, but o1js and Snarky pins differ from their corresponding acquired dependencies; no integrated release/build compatibility is claimed. Small retained proof size does not imply small application state, no witness-availability problem, or financial liveness.\n'''
p.write_text(p.read_text()+add)
p=c/'openspec/changes/consolidated-language-kernel/traceability.md';s=p.read_text()+'\n## Mina-derived refinement ownership\n\nAll rows are required through UNI-017 and their ZR clauses; status is specified-only.\n\n| ID | ZR | Owner | UNI | Status |\n|---|---|---|---|---|\n'
for id,title,zr,rule,test,ev,u in rows:s+=f'| {id} | {zr} | {u} | UNI-017 | specified-only |\n'
p.write_text(s)
p=c/'openspec/changes/consolidated-language-kernel/specs/consolidated-language-kernel/spec.md';s=p.read_text().replace('satisfy ZR01–ZR16 in the backend requirements contract','satisfy ZR01–ZR16 and MNR01–MNR08 in the backend requirements contract');p.write_text(s)
p=c/'openspec/changes/consolidated-language-kernel/requirements.md';p.write_text(p.read_text()+'\nMNR01–MNR08 are the Mina-derived mandatory refinements under UNI-017 and ZR01–ZR16; their owners and tests are recorded in the backend contract and traceability register.\n')
p=c/'ROADMAP.md';p.write_text(p.read_text()+'\nThe [Mina recursion case study](deliverables/mina-recursion-study-2026-09-19/RESULT.md) refines the same backend contract with MNR01–MNR08: transcript schedule, deferred obligations, compatible and authorized keys, verified-value binding, production mode, artifact provenance, batch soundness and component-level assurance. No Mina backend port is planned.\n')
p=c/'docs/MORIARTY-CONSOLIDATED-DESIGN.md';p.write_text(p.read_text()+'\nThe [Mina case study](../deliverables/mina-recursion-study-2026-09-19/RESULT.md) provides source-backed recursion failure cases and eight mandatory backend refinements. It strengthens this native Midnight architecture without changing the proof stack or relaxing the six-month full-recursion target.\n')
(r/'requirement-refinements.json').write_text(json.dumps([dict(zip(['id','title','zr','requirement','tests','evidence','owner'],x)) for x in rows],indent=2))
print('8 Mina refinements integrated')
