import test from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
import {PINNED_NM} from './providers.mjs';
const require=createRequire(join(PINNED_NM,'../package.json'));
const {Level}=require('level');
const accountId='synthetic-recovery-account';
const key='!sp05-loan:'+createHash('sha256').update(accountId).digest('hex').slice(0,32)+'!__midnight_encryption_metadata__';
const metadata=JSON.stringify({version:1,salt:'ab'.repeat(32)});
const snapshot=d=>fs.readdirSync(d).sort().map(n=>[n,fs.readFileSync(join(d,n)).toString('hex')]);
async function fixture(t,extra){const base=fs.mkdtempSync(join(tmpdir(),'recovery-store-fixture-'));fs.chmodSync(base,0o700);t.after(()=>fs.rmSync(base,{recursive:true,force:true}));const sourceDirectory=join(base,'source'),inspectionDirectory=join(base,'copy');const db=new Level(sourceDirectory);await db.open();await db.put(key,metadata);if(extra)await db.put(...extra);await db.close();fs.chmodSync(sourceDirectory,0o700);for(const n of fs.readdirSync(sourceDirectory))fs.chmodSync(join(sourceDirectory,n),0o600);return{base,sourceDirectory,inspectionDirectory,accountId};}
async function inspect(args){const api=await import('./recover-store.mjs').catch(()=>({}));assert.equal(typeof api.inspectFailedLoanStore,'function','bounded store inspector must exist');return api.inspectFailedLoanStore(args);}
test('metadata-only copied namespace passes with original bytes preserved and closed public result',async t=>{const f=await fixture(t),before=snapshot(f.sourceDirectory);const r=await inspect(f);assert.equal(r.status,'METADATA_ONLY');assert.deepEqual(snapshot(f.sourceDirectory),before);assert.match(r.sourceManifestSha256,/^[0-9a-f]{64}$/);assert.equal(r.sourceManifestSha256,r.copyManifestSha256);assert.equal(JSON.stringify(r).includes(f.base),false);assert.equal(JSON.stringify(r).includes('abababab'),false);assert.equal(fs.statSync(f.inspectionDirectory).mode&0o777,0o700);for(const n of fs.readdirSync(f.inspectionDirectory))assert.equal(fs.statSync(join(f.inspectionDirectory,n)).mode&0o777,0o600);});
test('unknown root entry rejects and retains copied evidence without changing original',async t=>{const f=await fixture(t,['unexpected','private-fixture']),before=snapshot(f.sourceDirectory);await assert.rejects(inspect(f),/RECOVERY_STORE/);assert.deepEqual(snapshot(f.sourceDirectory),before);assert.ok(fs.existsSync(f.inspectionDirectory));});
test('same path and nested paths reject before modification',async t=>{const f=await fixture(t);await assert.rejects(inspect({...f,inspectionDirectory:f.sourceDirectory}),/RECOVERY_STORE/);await assert.rejects(inspect({...f,inspectionDirectory:join(f.sourceDirectory,'nested')}),/RECOVERY_STORE/);});
test('existing destination is never reused',async t=>{const f=await fixture(t);fs.mkdirSync(f.inspectionDirectory,{mode:0o700});fs.writeFileSync(join(f.inspectionDirectory,'sentinel'),'preserved');await assert.rejects(inspect(f),/RECOVERY_STORE/);assert.equal(fs.readFileSync(join(f.inspectionDirectory,'sentinel'),'utf8'),'preserved');});
test('symlink source, ancestor and file reject',async t=>{const f=await fixture(t);const link=join(f.base,'link');fs.symlinkSync(f.sourceDirectory,link);await assert.rejects(inspect({...f,sourceDirectory:link}),/RECOVERY_STORE/);fs.unlinkSync(link);fs.symlinkSync(f.base,link);await assert.rejects(inspect({...f,sourceDirectory:join(link,'source')}),/RECOVERY_STORE/);fs.symlinkSync('CURRENT',join(f.sourceDirectory,'evil'));await assert.rejects(inspect(f),/RECOVERY_STORE/);});
test('nonprivate directory and file reject',async t=>{const f=await fixture(t);fs.chmodSync(f.sourceDirectory,0o755);await assert.rejects(inspect(f),/RECOVERY_STORE/);fs.chmodSync(f.sourceDirectory,0o700);fs.chmodSync(join(f.sourceDirectory,'CURRENT'),0o644);await assert.rejects(inspect(f),/RECOVERY_STORE/);});
test('wrong account rejects and preserves copy',async t=>{const f=await fixture(t);await assert.rejects(inspect({...f,accountId:'other'}),/RECOVERY_STORE/);assert.ok(fs.existsSync(f.inspectionDirectory));});
test('oversized file rejects before copy',async t=>{const f=await fixture(t);fs.writeFileSync(join(f.sourceDirectory,'oversized'),Buffer.alloc(1024*1024+1),{mode:0o600});await assert.rejects(inspect(f),/RECOVERY_STORE/);assert.equal(fs.existsSync(f.inspectionDirectory),false);});
test('unreadable Level copy is retained',async t=>{const f=await fixture(t);fs.writeFileSync(join(f.sourceDirectory,'CURRENT'),'invalid manifest\n');const before=snapshot(f.sourceDirectory);await assert.rejects(inspect(f),/RECOVERY_STORE/);assert.deepEqual(snapshot(f.sourceDirectory),before);assert.ok(fs.existsSync(f.inspectionDirectory));});
test('file count bound rejects before allocating inspection copy',async t=>{const f=await fixture(t);for(let i=0;i<33;i++)fs.writeFileSync(join(f.sourceDirectory,'extra-'+i),'',{mode:0o600});await assert.rejects(inspect(f),/RECOVERY_STORE_FILE_BOUND/);assert.equal(fs.existsSync(f.inspectionDirectory),false);});
test('metadata evidence filename collision retains exclusive copy on failure',async t=>{const f=await fixture(t);fs.writeFileSync(join(f.sourceDirectory,'.recovery-copy-manifest.json'),'fixture collision',{mode:0o600});const before=snapshot(f.sourceDirectory);await assert.rejects(inspect(f),/RECOVERY_STORE/);assert.deepEqual(snapshot(f.sourceDirectory),before);assert.equal(fs.readFileSync(join(f.inspectionDirectory,'.recovery-copy-manifest.json'),'utf8'),'fixture collision');});
test('private-state and signing-key entries reject',async t=>{for(const name of ['!sp05-loan!private-state','!signing-keys!key']){const f=await fixture(t,[name,'synthetic-private']);await assert.rejects(inspect(f),/RECOVERY_STORE/);assert.ok(fs.existsSync(f.inspectionDirectory));}});
test('metadata with unexpected shape rejects without disclosing contents',async t=>{const f=await fixture(t);const db=new Level(f.sourceDirectory);await db.open();await db.put(key,JSON.stringify({version:1,salt:'ab'.repeat(32),private:'do-not-disclose'}));await db.close();for(const n of fs.readdirSync(f.sourceDirectory))fs.chmodSync(join(f.sourceDirectory,n),0o600);const before=snapshot(f.sourceDirectory);await assert.rejects(inspect(f),e=>e.message==='RECOVERY_STORE_METADATA');assert.deepEqual(snapshot(f.sourceDirectory),before);});
async function emptyGate(){const api=await import('./recover-store.mjs');assert.equal(typeof api.assertEmptyRecoveryStore,'function','empty recovery destination gate must exist');return api.assertEmptyRecoveryStore;}
test('empty private recovery destination returns true without creating files',async t=>{const f=await fixture(t);fs.mkdirSync(f.inspectionDirectory,{mode:0o700});const gate=await emptyGate();assert.equal(gate(f.inspectionDirectory),true);assert.deepEqual(fs.readdirSync(f.inspectionDirectory),[]);});
test('nonempty recovery destination rejects and preserves records',async t=>{const f=await fixture(t);const before=snapshot(f.sourceDirectory),gate=await emptyGate();assert.throws(()=>gate(f.sourceDirectory),/RECOVERY_STORE_DESTINATION_NOT_EMPTY/);assert.deepEqual(snapshot(f.sourceDirectory),before);});
test('empty destination rejects symlink and symlink ancestor',async t=>{const f=await fixture(t);fs.mkdirSync(f.inspectionDirectory,{mode:0o700});const link=join(f.base,'link'),gate=await emptyGate();fs.symlinkSync(f.inspectionDirectory,link);assert.throws(()=>gate(link),/RECOVERY_STORE_DIRECTORY_SYMLINK/);fs.unlinkSync(link);fs.symlinkSync(f.base,link);assert.throws(()=>gate(join(link,'copy')),/RECOVERY_STORE_DIRECTORY_SYMLINK/);});
test('empty destination rejects loose permissions and relative paths',async t=>{const f=await fixture(t);fs.mkdirSync(f.inspectionDirectory,{mode:0o755});const gate=await emptyGate();assert.throws(()=>gate(f.inspectionDirectory),/RECOVERY_STORE_DIRECTORY_PRIVATE/);assert.throws(()=>gate('relative'),/RECOVERY_STORE_ABSOLUTE_PATH/);});
async function preserve(args){const api=await import('./recover-store.mjs');assert.equal(typeof api.preserveInitializedLoanStore,'function','initialized-store byte snapshot must exist');return api.preserveInitializedLoanStore(args);}
const contractAddress='ba4c808859fc2e4ee6d3d19fa0d812bb9a9c9eb0527161fb91315213bc24a713';
async function initializedFixture(t,mutate){
 const f=await fixture(t);for(const n of fs.readdirSync(f.sourceDirectory))fs.unlinkSync(join(f.sourceDirectory,n));
 const {levelPrivateStateProvider}=await import(join(PINNED_NM,'@midnight-ntwrk/midnight-js-level-private-state-provider/dist/index.mjs'));
 const provider=levelPrivateStateProvider({midnightDbName:f.sourceDirectory,privateStateStoreName:'sp05-loan',accountId,privateStoragePasswordProvider:()=> 'N7!kR4$vP9@xT6#bQ2'});
 provider.setContractAddress(contractAddress);await provider.set('sp05-loan',{});await provider.setSigningKey(contractAddress,'cd'.repeat(32));
 if(mutate){const db=new Level(f.sourceDirectory);await db.open();try{await mutate(db);}finally{await db.close();}}
 for(const n of fs.readdirSync(f.sourceDirectory))fs.chmodSync(join(f.sourceDirectory,n),0o600);
 return {...f,snapshotDirectory:join(f.base,'snapshot')};
}
const accountHash=createHash('sha256').update(accountId).digest('hex').slice(0,32);
const stateKey='!sp05-loan:'+accountHash+'!'+contractAddress+':sp05-loan';
const signingMetadata='!signing-keys:'+accountHash+'!__midnight_encryption_metadata__';
test('initialized store accepts actual SDK v2 namespace through separate inspection, preserving original and raw snapshot',async t=>{const f=await initializedFixture(t),before=snapshot(f.sourceDirectory);const r=await preserve(f);assert.deepEqual(r,{status:'PRESERVED',sourceManifestSha256:r.sourceManifestSha256,snapshotManifestSha256:r.sourceManifestSha256});assert.match(r.sourceManifestSha256,/^[a-f0-9]{64}$/);assert.deepEqual(snapshot(f.sourceDirectory),before);assert.deepEqual(snapshot(f.snapshotDirectory),before);assert.ok(fs.existsSync(f.inspectionDirectory));assert.equal(JSON.stringify(r).includes(f.base),false);assert.equal(JSON.stringify(r).includes('cdcdcd'),false);});
test('initialized inspection rejects missing, extra, plaintext, v1, mismatched-salt and malformed metadata without modifying source or snapshot',async t=>{for(const mutate of [db=>db.del(signingMetadata),db=>db.del(stateKey),db=>db.put('unknown','private'),db=>db.put(stateKey,'{}'),async db=>{const b=Buffer.from(await db.get(stateKey),'base64');b[0]=1;await db.put(stateKey,b.toString('base64'));},async db=>{const b=Buffer.from(await db.get(stateKey),'base64');b[1]^=1;await db.put(stateKey,b.toString('base64'));},db=>db.put(signingMetadata,JSON.stringify({salt:'ab',version:1})),db=>db.put(signingMetadata,JSON.stringify({salt:'ab'.repeat(32),version:2}))]){const f=await initializedFixture(t,mutate),before=snapshot(f.sourceDirectory);await assert.rejects(preserve(f),/RECOVERY_STORE/);assert.deepEqual(snapshot(f.sourceDirectory),before);assert.deepEqual(snapshot(f.snapshotDirectory),before);assert.ok(fs.existsSync(f.inspectionDirectory));}});
test('initialized copies reject reuse, overlaps, symlinks and loose permissions',async t=>{const f=await initializedFixture(t);for(const change of [{snapshotDirectory:f.sourceDirectory},{inspectionDirectory:f.snapshotDirectory},{inspectionDirectory:join(f.sourceDirectory,'nested')}])await assert.rejects(preserve({...f,...change}),/RECOVERY_STORE/);fs.mkdirSync(f.inspectionDirectory,{mode:0o700});await assert.rejects(preserve(f),/RECOVERY_STORE/);assert.equal(fs.existsSync(f.snapshotDirectory),false);fs.rmdirSync(f.inspectionDirectory);fs.symlinkSync('CURRENT',join(f.sourceDirectory,'evil'));await assert.rejects(preserve(f),/RECOVERY_STORE/);fs.unlinkSync(join(f.sourceDirectory,'evil'));fs.chmodSync(join(f.sourceDirectory,'CURRENT'),0o644);await assert.rejects(preserve(f),/RECOVERY_STORE/);assert.equal(fs.existsSync(f.snapshotDirectory),false);});
test('source and raw snapshot mutations during inspection are detected and retained',async t=>{for(const target of ['sourceDirectory','snapshotDirectory']){const f=await initializedFixture(t),open=Level.prototype.open;const mock=t.mock.method(Level.prototype,'open',function(...args){if(this.location===f.inspectionDirectory)fs.writeFileSync(join(f[target],'CURRENT'),'fixture mutation\n');return open.apply(this,args);});try{await assert.rejects(preserve(f),new RegExp(target==='sourceDirectory'?'RECOVERY_STORE_SOURCE_CHANGED':'RECOVERY_STORE_SNAPSHOT_CHANGED'));assert.ok(fs.existsSync(f.inspectionDirectory));}finally{mock.mock.restore();}}});
