[package]
name = "mori"
version = "0.1.0"
description = "Command-line interface for the Moriarty toolchain"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anstream.workspace = true
anstyle.workspace = true
clap.workspace = true
mori-diagnostics = { workspace = true, features = ["fancy"] }
