import json,hashlib
from pathlib import Path
r=Path('/home/charl/research/daml-teardown-2026-09-19');o=r/'studies/privacy-proof';manifest=json.load(open(r/'docs/batch-1-manifest.json'))
slugs={'overview':'overview/learn/privacy-model','appprivacy':'appdev/deep-dives/privacy-model','ledger':'overview/reference/ledger-model-detailed','disclosure':'appdev/deep-dives/explicit-contract-disclosure','upgrade':'appdev/deep-dives/smart-contract-upgrade','upref':'appdev/deep-dives/smart-contract-upgrading-reference','compat':'appdev/modules/m6-upgrade-compatibility','selection':'appdev/modules/m6-package-selection','interface':'appdev/modules/m3-interfaces','keys':'appdev/modules/m3-contract-keys'}
src={}
for k,s in slugs.items():
 m=next(x for x in manifest if x['url'].endswith('/'+s));p=r/m['text_file'];raw=r/m['raw_file']; h=hashlib.sha256(p.read_bytes()).hexdigest();assert h==m['text_sha256'];assert hashlib.sha256(raw.read_bytes()).hexdigest()==m['sha256'];src[k]={'source_id':k,'url':m['url'],'path':str(p),'sha256':h,'raw_path':str(raw),'raw_sha256':m['sha256'],'retrieved_at':m['retrieved_at'],'total_lines':len(p.read_text().splitlines()),'version':'current documentation snapshot 2026-09-19; not a release pin'}
pdf=r/'papers/daml-language.pdf'; paper={'source_id':'paper','url':'https://arxiv.org/pdf/2303.03749v1','path':str(pdf),'sha256':hashlib.sha256(pdf.read_bytes()).hexdigest(),'text_path':str(r/'papers/daml-language.txt'),'text_sha256':hashlib.sha256((r/'papers/daml-language.txt').read_bytes()).hexdigest(),'version':'arXiv:2303.03749v1, 7 March 2023','total_pages':14};src['paper']=paper

def ev(k,a,b=None):
 x=dict(src[k]);x['pages' if k=='paper' else 'lines']=[a,b or a];return x
claims=[
('DP01','Privacy follows informees and witnesses over action trees. An ancestor informee sees consequences, including contracts for which it is not a stakeholder; contract observers are not automatically informed of non-consuming exercises or fetches.','source-checked',[ev('ledger',1703,1849)]),
('DP02','The broad no-metadata-leakage language must be scoped: detailed ledger projections assume Ledger API-only observation; network/on-wire observation can reveal transaction shape, parties, encoding sizes, and confirmer information while transaction content remains confidential.','source-checked',[ev('overview',164,174),ev('overview',419,446),ev('appprivacy',28,44),ev('ledger',2009,2084)]),
('DP03','Explicit disclosure delegates read/lookup rights without relaxing Daml action authorization; disclosed-contract authentication binds contract contents to identity but business logic must separately validate expected issuer and asset.','source-checked',[ev('disclosure',287,346),ev('disclosure',409,462)]),
('DP04','Immediate divulgence does not imply disclosure for later submissions, because non-stakeholders may learn creation without subsequent archival; off-ledger disclosure and observer-list changes also disclose different counterparty relationships.','source-checked',[ev('ledger',1917,2006)]),
('DP05','A summary-returning audit choice is not by itself proof that the controller sees only the summary: action/input visibility and ancestor consequences must be evaluated.','inference',[ev('overview',325,357),ev('ledger',1774,1815),ev('ledger',1930,1942)]),
('DP06','Daml ledger validity separates consistency, conformance, and authorization. Full authorization is contextual; internal authorization and conformance have different projection behavior.','source-checked',[ev('ledger',575,596),ev('ledger',1360,1368),ev('ledger',1425,1602)]),
('DP07','The VGL guarantee is for honest parties under configured protocol/BFT assumptions; the detailed model explicitly does not guarantee global consistency for contracts whose signatories collude.','source-checked',[ev('ledger',1581,1625)]),
('DP08','SCU compatibility permits changed choice controllers/bodies and interface instance/view implementations. Data/metadata compatibility is not semantic equivalence or preservation of old signed intentions.','source-checked-and-inference',[ev('upgrade',88,193),ev('compat',48,76),ev('upref',794,900),ev('upref',1728,1801)]),
('DP09','Choice-body non-interface dispatch is statically selected by package dependencies; interface dispatch and eligible top-level commands use dynamic package selection. A fixed interface and v1 contract can return 1 or 2 under different preferred implementation versions.','source-checked',[ev('upref',903,1156),ev('upref',1157,1365),ev('upgrade',2678,2738)]),
('DP10','SCU runtime conversions add absent optional fields as None and reject dropping populated fields; metadata and ensure are rechecked. Unchanged stored contract identity does not imply unchanged execution semantics.','source-checked-and-inference',[ev('upref',1480,1726),ev('selection',17,51),ev('upgrade',1672,1706)]),
('DP11','Current Canton 3.x contract keys are not globally unique identity: multiple active contracts may share a key. Resolution prioritizes in-transaction creations, disclosures, then known contracts; None can also mean no visible contract.','source-checked',[ev('keys',22,62),ev('keys',130,217)]),
('DP12','The 2023 Daml paper presents Daml-LF formal typing/evaluation/authorization rules, runtime validation, and re-typechecking; this study finds no established machine-checked whole compiler/runtime theorem or proof-carrying ZKIRv3 compilation in the inspected paper.','bounded-negative-finding',[ev('paper',6,11),ev('paper',12,13)]),
('DP13','The paper keeps serializable ledger data first order, admits unrestricted recursion, and motivates auth checks before contract evaluation to avoid leaking data through errors. These design choices do not establish finite ZK circuit execution or noninterference automatically.','source-checked-and-inference',[ev('paper',7),ev('paper',9),ev('paper',11)]),
('DP14','The detailed ledger model explicitly treats the interoperability section as a vision under active development; its cross-ledger model must not be cited as proof of a current deployed cross-synchronizer or cross-chain protocol.','source-checked',[ev('ledger',2086,2097),ev('ledger',2259,2313),ev('ledger',2610,2635)]),
('DP15','The paper describes compiler/runtime/ledger layers and diverse trust assumptions; Daml language, Canton runtime/synchronization, Splice application standards, and a Midnight ZKIRv3 proof backend are separate assurance targets.','source-checked-and-inference',[ev('paper',2,3),ev('paper',10,13),ev('interface',32,39)]),
('DP16','Package vetting is participant-side operational compatibility/admission. It is not a universal theorem proving program correctness and is not a model for discretionary Moriarty developer approval.','source-checked-and-inference',[ev('selection',50,59),ev('upgrade',1237,1240)]),
]
(o/'claims.json').write_text(json.dumps({'study':'privacy-proof','as_of':'2026-09-19','claims':[{'id':i,'claim':c,'status':status,'confidence':'high' if status=='source-checked' else 'qualified-high','evidence':e}for i,c,status,e in claims]},indent=2))
coverage={'study':'privacy-proof','collected_batch_count':190,'read_current_documentation_pages':len(slugs),'documents':[dict(v,read_ranges=[[1,v['total_lines']]],status='full extracted-text page read; source-checked claims; no execution',html_layout_inspected=False)for k,v in src.items() if k!='paper'],'paper':dict(paper,text_read_pages=list(range(1,15)),pixelrag_rendered_pages=list(range(1,15)),visually_inspected_pages=[7,9,11],visual_files=[str(r/f'papers/pixelrag/daml-language.png.tiles/tile_{i-1:04}.jpg') for i in [7,9,11]],visual_notes={'7':'Typed update operations and first-order serializability rationale; ZK only hypothetical future discussion.','9':'Figure 4 transaction tree and displayed authorization rules; confirms S union C excludes ambient A; recursion subsection.','11':'Compiler LF re-typechecking and runtime authorization-before-evaluation ordering.'}), 'evidence_levels':{'collected':True,'text_read':True,'source_checked':True,'executed_examples':False,'machine_proofs_built':False,'implementation_correspondence_audited':False,'deployed_network_audited':False},'limitations':['HTML-to-text extraction flattens tables and contains malformed sample code; snippets were read as documentation, not certified compilable artifacts.','Detailed ledger model interoperability section explicitly describes active-development vision.','SCU default package selection wording varies across source pages; report uses explicit static/dynamic selection boundary and recommends pinned preference rather than claiming one universal default.','The 2023 paper predates current explicit-disclosure/SCU behavior; historical statements are version-scoped.']}
(o/'reading-coverage.json').write_text(json.dumps(coverage,indent=2))
proposals=[
{'key':'privacy-threat-model','disposition':'refine-existing','existing_ids':['MPLR-013'],'required_behavior':'Declare the observer/threat model for each confidentiality claim, including public statements, input contracts, descendant actions, errors, network shape, fees and status; make disclosure effects compositional.','positive_witness':'An authorized attestation stage exposes only declared attributes and an explicit leakage profile to the recipient and hosting service.','negative_witness':'An audit choice returns a summary but its input contract or fetched descendants disclose the underlying secret to the auditor.','source_claims':['DP01','DP02','DP05','DP13'],'pl_hypotheses':['Effect-indexed information-flow typing with declassification','Trace-based noninterference with explicit permitted leakage'],'midnight_obligations':['Bind statement fields and continuation commitments','Show ZKIRv3 witness/constraint noninterference against the chosen public trace','Include failed phases and external metadata in the observation relation']},
{'key':'read-authority-and-continuations','disposition':'refine-existing','existing_ids':['MPLR-008','MPLR-013'],'required_behavior':'Separate readable evidence, active evidence, authenticated provenance, action authority and witness availability for future stages. Prior disclosure must not silently confer spending authority or guarantee a continuation remains executable.','positive_witness':'A disclosed issuer-authenticated document supports a permitted predicate; a separately authorized callback consumes its bound continuation once.','negative_witness':'Possessing or having once observed a document authorizes transfer, or an archived/revoked document is accepted because its old payload hash remains valid.','source_claims':['DP03','DP04','DP06','DP11'],'pl_hypotheses':['Separate epistemic/read capabilities from affine action authority','Temporal evidence validity and availability obligations'],'midnight_obligations':['Check proof relation and evidence identity/freshness separately','Bind per-stage authority, nonce and external receipt correlation','Retain pending/unknown duties when evidence cannot be obtained']},
{'key':'semantic-evolution-and-signed-consent','disposition':'refine-existing-or-separate-candidate-after-deduplication','existing_ids':['MPLR-008','MPLR-014','MPLR-018'],'new_id':None,'required_behavior':'Bind the permitted implementation/semantics versions and migration relation to every outstanding authorization and continuation. Schema or interface compatibility alone shall not extend previously granted authority or alter signed outcomes.','positive_witness':'A semantics-preserving implementation change carries the required equivalence evidence, or a changed policy obtains fresh consent under an explicit amendment rule.','negative_witness':'A stable interface and contract ID select a new instance whose changed body weakens a settlement condition or changes fees after signing.','source_claims':['DP08','DP09','DP10','DP11'],'pl_hypotheses':['Behavioral refinement and contextual equivalence under version-indexed capabilities','Migration invariants preserving persistent liabilities and recovery options'],'midnight_obligations':['Pin program/semantics, proof key/circuit identity and target profile','Relate old continuation state to new state without erasing debts or residuals','Recertify jets when meaning/rejection/effects/cost changes']},
{'key':'assurance-layer-separation','disposition':'refine-existing','existing_ids':['MPLR-012','MPLR-014'],'required_behavior':'Report language semantics, static checks, runtime validation, cryptographic authorization, protocol assumptions, machine theorems and actual target acceptance as distinct evidence levels.','positive_witness':'The report states exactly which local predicate and source-to-constraint correspondence were proved and which external finality remains assumed.','negative_witness':'A formal rule, valid DAR, content hash, runtime simulation or package vetting is presented as a ZK execution proof or compiler theorem.','source_claims':['DP06','DP07','DP12','DP13','DP14','DP15','DP16'],'pl_hypotheses':['Layered refinement/correspondence judgments','Certified primitive composition with explicit preconditions and frame conditions'],'midnight_obligations':['Exclude every invalid satisfying witness, not only generate honest witnesses','Prove phase-aware traces including retained guaranteed effects','Demonstrate pinned ZKIRv3 and actual ledger verification']},
]
for q in proposals:q['evidence']=[e for cid in q['source_claims'] for c in claims if c[0]==cid for e in c[3]];q['status']='research proposal only; no ID allocated or vault mutation'
(o/'MPLR-candidates.json').write_text(json.dumps({'status':'draft proposals; existing IDs preserved; no new ID allocation','candidates':proposals},indent=2))
(o/'sources.json').write_text(json.dumps(src,indent=2));print('Wrote',len(claims),'claims,',len(slugs),'full-page read records, 4 candidate refinements.')
