[package]
name = "mori-fmt"
version = "0.1.0"
description = "Formatter for Moriarty source"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
mori-ast.workspace = true
mori-diagnostics.workspace = true
mori-lexer.workspace = true
mori-parser.workspace = true
mori-span.workspace = true
similar.workspace = true

[dev-dependencies]
indoc.workspace = true
insta.workspace = true
mori-diagnostics = { workspace = true, features = ["fancy"] }
proptest.workspace = true
