import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash,generateKeyPairSync,sign,ECDH} from 'node:crypto';
import {existsSync,mkdtempSync,writeFileSync,chmodSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {LocalSettlementStore,deriveSuccessorHead,validateSuccessor} from '../src/atomic.ts';
import {simulate} from '../src/bridge.ts';
import {transferSource,repaySource,transferScenario,repayScenario} from './fixtures.mjs';
// Positive tests use the real pinned native verifier. Keys are ephemeral and in memory only.
const binaryPath=process.env.MORIARTY_CRYPTO_BINARY??fileURLToPath(new URL('../../../experiments/midnight-crypto/target/debug/moriarty-midnight-crypto',import.meta.url));
const crypto={binaryPath};
const json=JSON.stringify,seen=[];
const NET={id:'Midnight',chain:'midnight',network:'preview'};
const N='0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141';
function keypair(){const {privateKey,publicKey}=generateKeyPairSync('ec',{namedCurve:'secp256k1'});const jwk=publicKey.export({format:'jwk'});
 const keyHex=ECDH.convertKey(Buffer.concat([Buffer.from([4]),Buffer.from(jwk.x,'base64url'),Buffer.from(jwk.y,'base64url')]),'secp256k1',undefined,'hex','compressed');
 return {keyHex,sign(messageHex){const bytes=sign('sha256',Buffer.from(messageHex,'hex'),{key:privateKey,dsaEncoding:'ieee-p1363'});const n=BigInt(N),s=BigInt('0x'+bytes.subarray(32).toString('hex'));if(s>n/2n)Buffer.from((n-s).toString(16).padStart(64,'0'),'hex').copy(bytes,32);return bytes.toString('hex');}};}
const owner=keypair(),payer=keypair(),attacker=keypair();
const canon=v=>Array.isArray(v)?'['+v.map(canon).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>json(k)+':'+canon(v[k])).join(',')+'}':json(v);
// Independent re-statement of the documented successor-head derivation.
function head(domain,preHead,frameSha256,effects){const p=Buffer.from(canon({domain,effects,frameSha256,preHead})),n=Buffer.alloc(4);n.writeUInt32BE(p.length);return createHash('sha256').update(Buffer.concat([Buffer.from('moriarty-local-successor/1\0'),n,p])).digest('hex');}
const bind=(id,account,key,over={})=>({bindingId:id,domain:NET,account,keyRef:'key1',scheme:'ecdsa_secp256k1_sha256',publicKeyHex:key.keyHex,validFromRound:'0',validUntilRound:'100',revokedFromRound:null,...over});
const registry=(rows,over={})=>json({profile:'moriarty-local-authority-bindings/1',kind:'local-stipulation',ledgerDomain:NET,revision:'0',bindings:rows,...over});
const OWNER=[bind('B1','Owner',owner)],PAYER=[bind('B2','Payer',payer)];
const mk=(scenario=transferScenario,rows=OWNER,options)=>new LocalSettlementStore(json(scenario),registry(rows),crypto,options);
const mkRepay=(scenario=repayScenario,options)=>mk(scenario,PAYER,options);
async function signed(store,source,action,key=owner,framing='raw'){
 const p=await store.prepareIntent({source,action,signing:{scheme:'ecdsa_secp256k1_sha256',publicKeyHex:key.keyHex,framing}});
 assert.equal(p.status,'OwnerIntentPrepared',json(p));return {text:json({statement:p.statement,signatureHex:key.sign(p.signing_message_hex)}),prepared:p};
}
const digestOf=s=>s.snapshot().stateDigest;
const req=(store,source,action,text,expectedStateDigest=digestOf(store))=>({source,action,signatureText:text,expectedStateDigest});
async function settle(store,source,action,text,digest){const r=await store.settle(req(store,source,action,text,digest));seen.push(json(r));return r;}
const pay=s=>settle(s.store,s.source??transferSource,'pay',s.text,s.digest);
const nonce=(src,n)=>src.replace('nonce: "n1"',`nonce: "${n}"`);
const preHead=(src,h)=>src.replace('pre_head: "h0"',`pre_head: "${h}"`);
const unchanged=(store,before)=>{assert.equal(json(store.snapshot()),json(before));};
const KEY='["Midnight","Owner","n1"]',PKEY='["Midnight","Payer","n1"]';
const PREMISES=['canonical-intent-signature','snapshot-to-head','head-extension','atomic-ledger-compare-and-consume'];
const BINDINGS=['agreement-id','selected-program','asset-scale','authenticated-predecessor'];
const base={core:'moriarty-core/5',domain:'Midnight',asset:'A',round:'1'};

test('pinned native verifier binary is present',()=>{assert.ok(existsSync(binaryPath),`missing ${binaryPath}; set MORIARTY_CRYPTO_BINARY`);});

// Five manually derived effect/post fixtures (S2 plan section 3), not generated by the code under test.
const fixtures=[
 ['fee transfer 1000+10',transferSource,'pay',transferScenario,owner,'Owner',KEY,
  h=>[{kind:'Debit',account:'Owner',asset:'A',amount:'1010'},{kind:'Credit',account:'Recipient',asset:'A',amount:'1000'},{kind:'Credit',account:'Fee',asset:'A',amount:'10'},{kind:'UseAllowance',owner:'Owner',amount:'1010'},{kind:'UseReplay',key:KEY}],
  {balances:[{account:'Owner',amount:'8990'},{account:'Recipient',amount:'1000'},{account:'Fee',amount:'10'}],allowances:[{owner:'Owner',remaining:'8990',spent:'1010'}],obligations:[]}],
 ['zero-fee transfer 1000',transferSource.replace('const fee = 0.10 USD;','const fee = 0.00 USD;'),'pay',transferScenario,owner,'Owner',KEY,
  h=>[{kind:'Debit',account:'Owner',asset:'A',amount:'1000'},{kind:'Credit',account:'Recipient',asset:'A',amount:'1000'},{kind:'UseAllowance',owner:'Owner',amount:'1000'},{kind:'UseReplay',key:KEY}],
  {balances:[{account:'Owner',amount:'9000'},{account:'Recipient',amount:'1000'},{account:'Fee',amount:'0'}],allowances:[{owner:'Owner',remaining:'9000',spent:'1000'}],obligations:[]}],
 ['repay 500 (accrual first, partial interest)',repaySource.replace('const amount = 30.00 USD;','const amount = 5.00 USD;'),'repay_loan',repayScenario,payer,'Payer',PKEY,
  h=>[{kind:'Debit',account:'Payer',asset:'A',amount:'500'},{kind:'Credit',account:'Creditor',asset:'A',amount:'500'},{kind:'SetObligation',id:'Loan',principal:'100000',accrued:'500',outstanding:'100500',status:'Outstanding'},{kind:'UseAllowance',owner:'Payer',amount:'500'},{kind:'UseReplay',key:PKEY}],
  {balances:[{account:'Payer',amount:'199500'},{account:'Creditor',amount:'500'}],allowances:[{owner:'Payer',remaining:'199500',spent:'500'}],obligations:[{id:'Loan',debtor:'Payer',creditor:'Creditor',asset:'A',principal:'100000',accrued:'500',outstanding:'100500',status:'Outstanding'}]}],
 ['repay 3000 (interest 1000 then principal 2000)',repaySource,'repay_loan',repayScenario,payer,'Payer',PKEY,
  h=>[{kind:'Debit',account:'Payer',asset:'A',amount:'3000'},{kind:'Credit',account:'Creditor',asset:'A',amount:'3000'},{kind:'SetObligation',id:'Loan',principal:'98000',accrued:'0',outstanding:'98000',status:'Outstanding'},{kind:'UseAllowance',owner:'Payer',amount:'3000'},{kind:'UseReplay',key:PKEY}],
  {balances:[{account:'Payer',amount:'197000'},{account:'Creditor',amount:'3000'}],allowances:[{owner:'Payer',remaining:'197000',spent:'3000'}],obligations:[{id:'Loan',debtor:'Payer',creditor:'Creditor',asset:'A',principal:'98000',accrued:'0',outstanding:'98000',status:'Outstanding'}]}],
 ['repay 101000 (full settlement)',repaySource.replace('const amount = 30.00 USD;','const amount = 1010.00 USD;'),'repay_loan',repayScenario,payer,'Payer',PKEY,
  h=>[{kind:'Debit',account:'Payer',asset:'A',amount:'101000'},{kind:'Credit',account:'Creditor',asset:'A',amount:'101000'},{kind:'SetObligation',id:'Loan',principal:'0',accrued:'0',outstanding:'0',status:'Settled'},{kind:'UseAllowance',owner:'Payer',amount:'101000'},{kind:'UseReplay',key:PKEY}],
  {balances:[{account:'Payer',amount:'99000'},{account:'Creditor',amount:'101000'}],allowances:[{owner:'Payer',remaining:'99000',spent:'101000'}],obligations:[{id:'Loan',debtor:'Payer',creditor:'Creditor',asset:'A',principal:'0',accrued:'0',outstanding:'0',status:'Settled'}]}],
];
for(const [name,source,action,scenario,key,account,replayKey,effects,post] of fixtures)test(`fixture ${name}: hand effects, derived head, post state and Core5 cross-check`,async()=>{
 const store=mk(scenario,[bind('B',account,key)]),pre=store.snapshot(),{text,prepared}=await signed(store,source,action,key);
 const r=await settle(store,source,action,text);
 assert.equal(r.status,'LocalCommitted',json(r));
 const h1=head(NET,'h0',prepared.frame_sha256,effects());
 assert.deepEqual(r.effects,[...effects(),{kind:'AdvanceHead',predecessor:'h0',successor:h1}]);
 assert.equal(r.head,h1);assert.equal(r.frameSha256,prepared.frame_sha256);assert.equal(r.replayKey,replayKey);
 const s=r.snapshot;
 assert.deepEqual(s.state,{...base,head:h1,workRemaining:'9',workSpent:'1',consumedReplay:[replayKey],...post});
 assert.equal(s.predecessor,'h0');assert.equal(s.provenance,'local-stipulation');
 assert.equal(r.preStateDigest,pre.stateDigest);assert.equal(r.postStateDigest,s.stateDigest);assert.notEqual(r.postStateDigest,r.preStateDigest);
 assert.equal(json(store.snapshot()),json(s));
 // Same inputs through Core5 directly (bridge) with the derived head: byte-equal effects and post-state.
 const core=simulate(source,action,json({...scenario,post_head:h1})).result.candidate;
 assert.equal(json(core.effects),json(r.effects));assert.equal(json(core.candidatePost),json(s.state));
 assert.deepEqual(r.requiredPremises,PREMISES);assert.deepEqual(r.unverifiedBindings,BINDINGS);
 assert.equal(r.ledger_accepted,false);assert.equal(r.authority_valid,null);assert.equal(r.localAuthorityMatched,true);assert.equal(r.qualification,'local-stipulation');assert.equal(r.signature_valid,true);
 assert.equal(s.receipts[replayKey].frameSha256,prepared.frame_sha256);
});

test('construction bounds and closed schemas',()=>{
 const bad=(scenario,regs,options)=>assert.throws(()=>new LocalSettlementStore(typeof scenario==='string'?scenario:json(scenario),typeof regs==='string'?regs:registry(...regs),crypto,options),{code:/^(ATOMIC_CONFIG|BETA_JSON)/});
 bad({...transferScenario,extra:true},[OWNER]);bad({...transferScenario,replay:'consumed'},[OWNER]);bad({...transferScenario,domain:'Other'},[OWNER]);
 bad(json(transferScenario).replace('"head":"h0"','"head":"h0","head":"h1"'),[OWNER]);
 bad(transferScenario,[[{...OWNER[0],trusted:true}]]);bad(transferScenario,[[OWNER[0],OWNER[0]]]);
 bad(transferScenario,[[{...OWNER[0],publicKeyHex:'00'}]]);bad(transferScenario,[[{...OWNER[0],scheme:'schnorr_bip340'}]]);
 bad(transferScenario,[[{...OWNER[0],validFromRound:'9',validUntilRound:'3'}]]);bad(transferScenario,[[{...OWNER[0],domain:{id:'Midnight',chain:'midnight'}}]]);
 bad(transferScenario,[[OWNER[0]],{ledgerDomain:{id:'Other',chain:'midnight',network:'preview'}}]);bad(transferScenario,[[OWNER[0]],{kind:'ledger'}]);
 bad(transferScenario,[[OWNER[0]],{revision:'01'}]);
 assert.throws(()=>new LocalSettlementStore(json(transferScenario),registry(OWNER),{binaryPath:'cargo'}),{code:'BETA_CRYPTO_BINARY_PATH'});
 assert.throws(()=>new LocalSettlementStore(json(transferScenario),registry(OWNER),crypto,{signatureValid:()=>true}),{code:'ATOMIC_CONFIG_SCHEMA'});
 assert.throws(()=>new LocalSettlementStore(json(transferScenario),registry(OWNER),crypto,{faultHook:true}),{code:'ATOMIC_CONFIG_SCHEMA'});
});

test('crypto configuration is copied; later mutation cannot redirect the verifier',async()=>{
 const config={binaryPath};const store=new LocalSettlementStore(json(transferScenario),registry(OWNER),config);config.binaryPath='/tmp/evil';
 const {text}=await signed(store,transferSource,'pay');const r=await settle(store,transferSource,'pay',text);assert.equal(r.status,'LocalCommitted');
});

test('snapshots are immutable clones with local-stipulation provenance only',async()=>{
 const store=mk(),s=store.snapshot();
 assert.equal(s.provenance,'local-stipulation');assert.equal(s.ledger_accepted,false);assert.equal(s.authority_valid,null);assert.equal(s.qualification,'local-stipulation');
 assert.ok(Object.isFrozen(s)&&Object.isFrozen(s.state)&&Object.isFrozen(s.state.balances)&&Object.isFrozen(s.state.balances[0])&&Object.isFrozen(s.registry.bindings[0]));
 assert.throws(()=>{s.state.balances[0].amount='9';});assert.throws(()=>{s.state.balances.push({});});assert.throws(()=>{s.provenance='ledger';});
 assert.deepEqual(s.registry,{revision:'0',bindings:[{...OWNER[0]}]});assert.deepEqual(s.ledgerDomain,NET);
 const {text}=await signed(store,transferSource,'pay');assert.equal((await settle(store,transferSource,'pay',text,s.stateDigest)).status,'LocalCommitted');
 assert.equal(s.state.balances[0].amount,'10000');assert.equal(s.state.head,'h0');assert.notEqual(store.snapshot().stateDigest,s.stateDigest);
});

test('state digest covers state, receipts, registry revision and bindings',()=>{
 const d=(scenario,over)=>new LocalSettlementStore(json(scenario),registry(OWNER,over),crypto).snapshot().stateDigest;
 const ref=d(transferScenario);assert.equal(ref,d(transferScenario));assert.match(ref,/^[a-f0-9]{64}$/);
 const changes={balance:{...transferScenario,balances:[{account:'Owner',amount:'9999'},...transferScenario.balances.slice(1)]},
  allowance:{...transferScenario,allowance:{owner:'Owner',remaining:'9999',spent:'1'}},work:{...transferScenario,work_remaining:'9'},workSpent:{...transferScenario,work_spent:'1'},
  head:{...transferScenario,head:'h9'},predecessor:{...transferScenario,predecessor:'g9'},round:{...transferScenario,round:'2'}};
 for(const [k,scenario] of Object.entries(changes))assert.notEqual(d(scenario),ref,k);
 assert.equal(d({...transferScenario,post_head:'ignored'}),ref);
 assert.notEqual(d(transferScenario,{revision:'1'}),ref);
 assert.notEqual(new LocalSettlementStore(json(transferScenario),registry([bind('B1','Owner',owner,{validUntilRound:'99'})]),crypto).snapshot().stateDigest,ref);
 assert.notEqual(new LocalSettlementStore(json(transferScenario),registry([bind('B1','Owner',owner,{keyRef:'key2'})]),crypto).snapshot().stateDigest,ref);
});

test('owner bytes are state independent: equal statement/frame across different stores',async()=>{
 const a=mk(),b=mk({...transferScenario,balances:[{account:'Owner',amount:'1'},{account:'Recipient',amount:'7'},{account:'Fee',amount:'8'}],allowance:{owner:'Owner',remaining:'5',spent:'5'},work_remaining:'0',work_spent:'3',round:'77',head:'zzz',predecessor:'p'});
 const pa=await a.prepareIntent({source:transferSource,action:'pay',signing:{scheme:'ecdsa_secp256k1_sha256',publicKeyHex:owner.keyHex,framing:'raw'}});
 const pb=await b.prepareIntent({source:transferSource,action:'pay',signing:{scheme:'ecdsa_secp256k1_sha256',publicKeyHex:owner.keyHex,framing:'raw'}});
 for(const k of ['statement','frame_hex','frame_sha256','signing_message_hex'])assert.equal(json(pa[k]),json(pb[k]),k);
 assert.equal(pa.stateDigest,digestOf(a));assert.notEqual(pa.stateDigest,pb.stateDigest);assert.equal(pa.statement.domain.network,'preview');
 const store=mkRepay(),done=await signed(store,fixtures[4][1],'repay_loan',payer);
 assert.equal((await settle(store,fixtures[4][1],'repay_loan',done.text)).status,'LocalCommitted');
 const after=await store.prepareIntent({source:fixtures[4][1],action:'repay_loan',signing:{scheme:'ecdsa_secp256k1_sha256',publicKeyHex:payer.keyHex,framing:'raw'}});
 assert.equal(after.frame_sha256,done.prepared.frame_sha256);
 await assert.rejects(a.prepareIntent({source:transferSource,action:'pay',signing:{scheme:'ecdsa_secp256k1_sha256',publicKeyHex:owner.keyHex,framing:'raw'},extra:true}),{code:'ATOMIC_INPUT_SCHEMA'});
});

test('closed settle input rejects invented flags and malformed values; nothing changes',async()=>{
 const store=mk(),{text}=await signed(store,transferSource,'pay'),good=req(store,transferSource,'pay',text);
 for(const extra of [{signatureValid:true},{authorityValid:true},{ledger_accepted:true},{qualification:'LedgerCommitted'},{skipChecks:true},{nonceFresh:true},{checks:{signatureValid:true}},{post:{}},{localAuthorityMatched:true}]){
  const rr=await store.settle({...good,...extra});seen.push(json(rr));assert.equal(rr.status,'Rejected');assert.equal(rr.layer,'input');assert.equal(rr.code,'ATOMIC_INPUT_SCHEMA',json(extra));
 }
});
test('closed settle input: missing/ill-typed/oversize/accessor/array/prototype values refused',async()=>{
 const store=mk(),before=store.snapshot(),{text}=await signed(store,transferSource,'pay'),good=req(store,transferSource,'pay',text);
 const accessor={...good};Object.defineProperty(accessor,'source',{enumerable:true,get(){return transferSource;}});
 const sym={...good,[Symbol('x')]:1};
 for(const bad of [null,undefined,'x',[],[good],{...good,source:5},{...good,action:'bad action'},{...good,action:''},{...good,signatureText:'x'.repeat(65537)},{...good,source:'x'.repeat(65537)},{...good,expectedStateDigest:'ABC'},{...good,expectedStateDigest:good.expectedStateDigest.toUpperCase()},{...good,expectedStateDigest:'0x'+good.expectedStateDigest.slice(2)},
  (({source,...rest})=>rest)(good),(({expectedStateDigest,...rest})=>rest)(good),accessor,sym,Object.create(good),new Map(),()=>good]){
  const r=await store.settle(bad);seen.push(json(r));assert.equal(r.status,'Rejected');assert.equal(r.layer,'input');assert.equal(r.code,'ATOMIC_INPUT_SCHEMA');
 }
 unchanged(store,before);
});

// R1: same intent delivered twice concurrently.
test('R1 same artifact twice concurrently: one LocalCommitted, exact repeat AlreadyCommitted, one effect',async()=>{
 const store=mk(),{text}=await signed(store,transferSource,'pay'),d=digestOf(store);
 const rs=await Promise.all([settle(store,transferSource,'pay',text,d),settle(store,transferSource,'pay',text,d)]);
 assert.deepEqual(rs.map(r=>r.status).sort(),['AlreadyCommitted','LocalCommitted']);
 const [win,rep]=rs[0].status==='LocalCommitted'?rs:[rs[1],rs[0]];
 assert.equal(rep.head,win.head);assert.equal(rep.frameSha256,win.frameSha256);assert.equal(rep.ledger_accepted,false);assert.equal(rep.authority_valid,null);
 const s=store.snapshot();assert.equal(s.state.balances[0].amount,'8990');assert.equal(s.state.workSpent,'1');assert.deepEqual(s.state.consumedReplay,[KEY]);
 assert.equal(s.stateDigest,win.postStateDigest);
});
test('R1b eight concurrent identical deliveries: exactly one effect',async()=>{
 const store=mk(),{text}=await signed(store,transferSource,'pay'),d=digestOf(store);
 const rs=await Promise.all(Array.from({length:8},()=>settle(store,transferSource,'pay',text,d)));
 assert.equal(rs.filter(r=>r.status==='LocalCommitted').length,1);assert.equal(rs.filter(r=>r.status==='AlreadyCommitted').length,7);
 assert.equal(store.snapshot().state.balances[0].amount,'8990');
});
// R2: two intents with the same preHead race.
test('R2 two different intents (n1,n2) with same preHead: one commits, loser ATOMIC_STALE_STATE and no effect',async()=>{
 const store=mk(),b=nonce(transferSource,'n2'),a=await signed(store,transferSource,'pay'),c=await signed(store,b,'pay'),d=digestOf(store);
 const rs=await Promise.all([settle(store,transferSource,'pay',a.text,d),settle(store,b,'pay',c.text,d)]);
 const won=rs.filter(r=>r.status==='LocalCommitted'),lost=rs.filter(r=>r.status==='Rejected');
 assert.equal(won.length,1,json(rs));assert.equal(lost.length,1);assert.equal(lost[0].code,'ATOMIC_STALE_STATE');assert.equal(lost[0].layer,'atomic');
 const s=store.snapshot();assert.equal(s.state.consumedReplay.length,1);assert.equal(s.state.balances[0].amount,'8990');assert.equal(s.state.workSpent,'1');
 const late=await settle(store,rs[0].status==='Rejected'?transferSource:b,'pay',rs[0].status==='Rejected'?a.text:c.text,d);
 assert.equal(late.status,'Rejected');assert.equal(late.code,'ATOMIC_STALE_STATE');
});
test('R2b same nonce, different statement, concurrently: loser is ATOMIC_STALE_STATE, never AlreadyCommitted',async()=>{
 const store=mk(),other=transferSource.replace('const price: Qty<USD> = 10.00 USD;','const price: Qty<USD> = 9.00 USD;'),a=await signed(store,transferSource,'pay'),b=await signed(store,other,'pay'),d=digestOf(store);
 const rs=await Promise.all([settle(store,transferSource,'pay',a.text,d),settle(store,other,'pay',b.text,d)]);
 assert.equal(rs.filter(r=>r.status==='LocalCommitted').length,1,json(rs));
 const lost=rs.find(r=>r.status!=='LocalCommitted');assert.equal(lost.status,'Rejected');assert.equal(lost.code,'ATOMIC_STALE_STATE');
 assert.equal(store.snapshot().state.consumedReplay.length,1);assert.equal(Object.keys(store.snapshot().receipts).length,1);
});
test('stale expected digest is refused before any native process is spawned',async()=>{
 const gone=new LocalSettlementStore(json(transferScenario),registry(OWNER),{binaryPath:'/nonexistent/moriarty-native-verifier'}),text=(await signed(mk(),transferSource,'pay')).text;
 const r=await settle(gone,transferSource,'pay',text,'0'.repeat(64));assert.equal(r.code,'ATOMIC_STALE_STATE');assert.equal(r.layer,'atomic');
});
// R3 and statement-binding of replay.
test('R3 same nonce re-signed with preHead=h1 is S0_HISTORY_REPLAY; changed statement with old head is stale; neither consumes',async()=>{
 const store=mk(),a=await signed(store,transferSource,'pay'),first=await settle(store,transferSource,'pay',a.text);assert.equal(first.status,'LocalCommitted');
 const before=store.snapshot(),again=preHead(transferSource,first.head),b=await signed(store,again,'pay');
 const r=await settle(store,again,'pay',b.text);assert.equal(r.status,'Rejected');assert.equal(r.layer,'core');assert.equal(r.code,'S0_HISTORY_REPLAY');unchanged(store,before);
 const other=transferSource.replace('const price: Qty<USD> = 10.00 USD;','const price: Qty<USD> = 9.00 USD;'),c=await signed(store,other,'pay');
 const q=await settle(store,other,'pay',c.text);assert.equal(q.status,'Rejected');assert.equal(q.code,'S0_HISTORY_STALE');unchanged(store,before);
});
test('R4 allowance 1500 allows one gross-1010 transfer; second is S0_AUTH_SCOPE after first only',async()=>{
 const store=mk({...transferScenario,allowance:{owner:'Owner',remaining:'1500',spent:'0'}}),a=await signed(store,transferSource,'pay'),r1=await settle(store,transferSource,'pay',a.text);assert.equal(r1.status,'LocalCommitted');
 assert.deepEqual(store.snapshot().state.allowances,[{owner:'Owner',remaining:'490',spent:'1010'}]);const before=store.snapshot();
 const s2=preHead(nonce(transferSource,'n2'),r1.head),b=await signed(store,s2,'pay'),r2=await settle(store,s2,'pay',b.text);
 assert.equal(r2.status,'Rejected');assert.equal(r2.code,'S0_AUTH_SCOPE');unchanged(store,before);
});
test('R5 workRemaining 0 is S0_AUTH_SCOPE; R6 balance 1009 < gross 1010 is S0_EFFECT_RANGE; R8 round 11 is S0_INTENT_SCOPE',async()=>{
 for(const [scenario,code] of [[{...transferScenario,work_remaining:'0'},'S0_AUTH_SCOPE'],[{...transferScenario,balances:[{account:'Owner',amount:'1009'},{account:'Recipient',amount:'0'},{account:'Fee',amount:'0'}]},'S0_EFFECT_RANGE'],[{...transferScenario,round:'11'},'S0_INTENT_SCOPE']]){
  const store=mk(scenario),before=store.snapshot(),a=await signed(store,transferSource,'pay'),r=await settle(store,transferSource,'pay',a.text);
  assert.equal(r.status,'Rejected');assert.equal(r.layer,'core');assert.equal(r.code,code);assert.equal(r.signature_valid,true);unchanged(store,before);
 }
});
// R7: binding revoked between prepare and commit.
test('R7 revocation racing an in-flight settle refuses with AUTH_REVOKED and consumes nothing',async()=>{
 const store=mk(),a=await signed(store,transferSource,'pay'),d=digestOf(store),core=store.snapshot().state;
 const pending=settle(store,transferSource,'pay',a.text,d),rev=store.revoke({bindingId:'B1'});
 const [r,v]=await Promise.all([pending,rev]);
 assert.equal(v.status,'LocalBindingRevoked');assert.equal(r.status,'Rejected');assert.equal(r.layer,'authority');assert.equal(r.code,'AUTH_REVOKED');assert.equal(r.signature_valid,true);
 const s=store.snapshot();assert.equal(json(s.state),json(core));assert.deepEqual(s.receipts,{});assert.equal(s.registry.revision,'1');assert.equal(s.registry.bindings[0].revokedFromRound,'1');
 const after=await settle(store,transferSource,'pay',a.text);assert.equal(after.code,'AUTH_REVOKED');
});
test('R7b revoke API: unknown ids, closed input, monotone revision, effective round semantics',async()=>{
 const store=mk(),before=store.snapshot();
 for(const bad of [{bindingId:'nope'},{bindingId:'B1',extra:1},{bindingId:'B1',fromRound:'-1'},{bindingId:'B1',fromRound:1},{},null,{bindingId:'B1',fromRound:'0',valid:true}]){const r=await store.revoke(bad);assert.equal(r.status,'Rejected',json(bad));}
 unchanged(store,before);
 const r=await store.revoke({bindingId:'B1',fromRound:'5'});assert.equal(r.status,'LocalBindingRevoked');assert.equal(r.registryRevision,'1');assert.equal(r.revokedFromRound,'5');
 const a=await signed(store,transferSource,'pay');assert.equal((await settle(store,transferSource,'pay',a.text)).status,'LocalCommitted');// round 1 < 5
 const r2=await store.revoke({bindingId:'B1',fromRound:'9'});assert.equal(r2.revokedFromRound,'5');assert.equal(r2.registryRevision,'2');
 const r3=await store.revoke({bindingId:'B1',fromRound:'1'});assert.equal(r3.revokedFromRound,'1');
});
test('revocation at, before and after the state round',async()=>{
 for(const [from,expect] of [['0','AUTH_REVOKED'],['1','AUTH_REVOKED'],['2','LocalCommitted']]){
  const store=new LocalSettlementStore(json(transferScenario),registry([bind('B1','Owner',owner,{revokedFromRound:from})]),crypto),a=await signed(store,transferSource,'pay'),r=await settle(store,transferSource,'pay',a.text);
  assert.equal(r.status==='Rejected'?r.code:r.status,expect);
 }
});
// R9/R10 and the binding matrix: attacker, key, scheme, network, validity.
test('R9 attacker with a native-valid signature under a different key is AUTH_KEY_MISMATCH; wrong-key signature over owner key is SIGNATURE_INVALID',async()=>{
 const store=mk(),before=store.snapshot(),a=await signed(store,transferSource,'pay',attacker),r=await settle(store,transferSource,'pay',a.text);
 assert.equal(r.status,'Rejected');assert.equal(r.layer,'authority');assert.equal(r.code,'AUTH_KEY_MISMATCH');assert.equal(r.signature_valid,true);unchanged(store,before);
 const mine=await signed(store,transferSource,'pay',owner),forged=json({statement:JSON.parse(mine.text).statement,signatureHex:attacker.sign(mine.prepared.signing_message_hex)});
 const f=await settle(store,transferSource,'pay',forged);assert.equal(f.status,'Rejected');assert.equal(f.layer,'signature');assert.equal(f.code,'SIGNATURE_INVALID');assert.equal(f.signature_valid,false);unchanged(store,before);
});
const matrix=[
 ['no binding for keyRef',transferScenario,[bind('B1','Owner',owner,{keyRef:'other'})],transferSource,'AUTH_NO_BINDING'],
 ['binding for a different account',transferScenario,[bind('B1','Recipient',owner)],transferSource,'AUTH_NO_BINDING'],
 ['wrong network binding',transferScenario,[bind('B1','Owner',owner,{domain:{...NET,network:'mainnet'}})],transferSource,'AUTH_DOMAIN_MISMATCH'],
 ['wrong chain binding',transferScenario,[bind('B1','Owner',owner,{domain:{...NET,chain:'cardano'}})],transferSource,'AUTH_DOMAIN_MISMATCH'],
 ['wrong domain id binding',transferScenario,[bind('B1','Owner',owner,{domain:{...NET,id:'Other'}})],transferSource,'AUTH_DOMAIN_MISMATCH'],
 ['source network differs from the ledger',transferScenario,OWNER,transferSource.replace('network: "preview"','network: "mainnet"'),'AUTH_DOMAIN_MISMATCH'],
 ['source chain differs from the ledger',transferScenario,OWNER,transferSource.replace('chain: "midnight"','chain: "cardano"'),'AUTH_DOMAIN_MISMATCH'],
 ['cross-network replay: binding registered for another network and a source naming it',transferScenario,[bind('B1','Owner',owner,{domain:{...NET,network:'mainnet'}})],transferSource.replace('network: "preview"','network: "mainnet"'),'AUTH_DOMAIN_MISMATCH'],
 ['scheme differs',transferScenario,[bind('B1','Owner',owner,{scheme:'schnorr_bip340',publicKeyHex:'ab'.repeat(32)})],transferSource,'AUTH_KEY_MISMATCH'],
 ['public key differs',transferScenario,[bind('B1','Owner',attacker)],transferSource,'AUTH_KEY_MISMATCH'],
 ['expired',transferScenario,[bind('B1','Owner',owner,{validUntilRound:'0'})],transferSource,'AUTH_EXPIRED'],
 ['not yet valid',transferScenario,[bind('B1','Owner',owner,{validFromRound:'2'})],transferSource,'AUTH_NOT_YET_VALID'],
 ['revoked from the round',transferScenario,[bind('B1','Owner',owner,{revokedFromRound:'1'})],transferSource,'AUTH_REVOKED'],
];
for(const [name,scenario,rows,source,code] of matrix)test(`binding matrix: ${name} -> ${code}`,async()=>{
 const store=mk(scenario,rows),before=store.snapshot(),a=await signed(store,source,'pay'),r=await settle(store,source,'pay',a.text);
 assert.equal(r.status,'Rejected',json(r));assert.equal(r.layer,'authority');assert.equal(r.code,code);assert.equal(r.signature_valid,true);assert.equal(r.localAuthorityMatched??false,false);unchanged(store,before);
});
test('domain id in source that differs from the store is a source-layer refusal',async()=>{
 const store=mk(),before=store.snapshot(),src=transferSource.replace('id: "Midnight"','id: "Elsewhere"'),r=await store.settle(req(store,src,'pay','{}'));seen.push(json(r));
 assert.equal(r.status,'Rejected');assert.equal(r.layer,'source');assert.match(r.code,/^BETA_/);unchanged(store,before);
});
test('midnight-sign-data framing settles with the same binding and a different frame-bound head',async()=>{
 const store=mk(),a=await signed(store,transferSource,'pay',owner,'midnight-sign-data'),r=await settle(store,transferSource,'pay',a.text);assert.equal(r.status,'LocalCommitted',json(r));
 const raw=await mk().prepareIntent({source:transferSource,action:'pay',signing:{scheme:'ecdsa_secp256k1_sha256',publicKeyHex:owner.keyHex,framing:'raw'}});
 assert.notEqual(r.head,head(NET,'h0',raw.frame_sha256,r.effects.slice(0,-1)));
});
// Signature and source tampering.
test('tampering: statement, source, signature and digest are refused before any write',async()=>{
 const store=mk(),before=store.snapshot(),a=await signed(store,transferSource,'pay'),art=JSON.parse(a.text);
 const mut=(f)=>{const c=structuredClone(art);f(c);return json(c);};
 for(const [label,text,source,code,layer] of [
  ['statement preHead',mut(c=>{c.statement.intent.preHead='h1';}),transferSource,'BETA_SIGNATURE_SOURCE_MISMATCH','verification'],
  ['statement amount',mut(c=>{c.statement.intent.operation.amount='1';}),transferSource,'BETA_SIGNATURE_SOURCE_MISMATCH','verification'],
  ['statement domain network',mut(c=>{c.statement.domain.network='mainnet';}),transferSource,'BETA_SIGNATURE_SOURCE_MISMATCH','verification'],
  ['source whitespace',a.text,transferSource+'\n','BETA_SIGNATURE_SOURCE_MISMATCH','verification'],
  ['signature bit',mut(c=>{c.signatureHex=(c.signatureHex.startsWith('01')?'02':'01')+c.signatureHex.slice(2);}),transferSource,'SIGNATURE_INVALID','signature'],
  ['extra artifact field',mut(c=>{c.authorityValid=true;}),transferSource,'BETA_CRYPTO_RESPONSE','verification'],
  ['not json','not json',transferSource,'BETA_JSON_SYNTAX','verification'],
 ]){
  const r=await settle(store,source,'pay',text);assert.equal(r.status,'Rejected',label);assert.equal(r.layer,layer,label);
  if(layer==='verification')assert.match(r.code,/^BETA_/,label);else assert.equal(r.code,code,label);
  assert.equal(r.signature_valid,layer==='signature'?false:null,label);unchanged(store,before);
 }
 const wrong=await store.settle(req(store,transferSource,'pay',a.text,'0'.repeat(64)));seen.push(json(wrong));assert.equal(wrong.code,'ATOMIC_STALE_STATE');unchanged(store,before);
});
test('transport faults leave signature validity unknown and never commit (fake binary: transport negatives only)',async()=>{
 const temp=mkdtempSync(join(tmpdir(),'mori-atomic-'));
 try{
  for(const [name,body,timeoutMs] of [['timeout','setInterval(()=>{},1000)',30],['authority claim',`console.log('{"status":"IntentBuilt","authority_valid":true}')`,2000],['invalid utf8','process.stdout.write(Buffer.from([255,10]))',2000]]){
   const file=join(temp,name.replace(/ /g,'_'));writeFileSync(file,`#!${process.execPath}\nprocess.stdin.resume();process.stdin.on('end',()=>{${body}});\n`);chmodSync(file,0o755);
   const store=new LocalSettlementStore(json(transferScenario),registry(OWNER),{binaryPath:file,timeoutMs}),before=store.snapshot();
   const real=mk(),{text}=await signed(real,transferSource,'pay');
   const r=await settle(store,transferSource,'pay',text,digestOf(store));assert.equal(r.status,'Rejected',name);assert.equal(r.layer,'verification');assert.match(r.code,/^BETA_CRYPTO_/,name);assert.equal(r.signature_valid,null);unchanged(store,before);
  }
  const gone=new LocalSettlementStore(json(transferScenario),registry(OWNER),{binaryPath:'/nonexistent/moriarty-native-verifier'}),b2=gone.snapshot();
  const signedText=(await signed(mk(),transferSource,'pay')).text,r=await settle(gone,transferSource,'pay',signedText,digestOf(gone));assert.equal(r.code,'BETA_CRYPTO_BINARY_UNAVAILABLE');assert.equal(r.signature_valid,null);unchanged(gone,b2);
 }finally{rmSync(temp,{recursive:true,force:true});}
});
// R11/R12/R13: crash, ack loss and faults.
test('R11 fault before commit leaves state byte-identical; retry commits exactly once with the same head',async()=>{
 const steps=[];let fail=true;const store=mk(transferScenario,OWNER,{faultHook:s=>{steps.push(s);if(fail&&s==='balances')throw new Error('disk');}});
 const before=store.snapshot(),a=await signed(store,transferSource,'pay'),r=await settle(store,transferSource,'pay',a.text);
 assert.equal(r.status,'Rejected');assert.equal(r.layer,'atomic');assert.equal(r.code,'ATOMIC_COMMIT_FAULT');unchanged(store,before);
 fail=false;const ok=await settle(store,transferSource,'pay',a.text);assert.equal(ok.status,'LocalCommitted');
 assert.equal(ok.head,head(NET,'h0',a.prepared.frame_sha256,ok.effects.slice(0,-1)));
 assert.deepEqual(steps.slice(-8),['balances','allowances','obligations','replay','work','head','receipt','swap']);
});
for(const step of ['balances','allowances','obligations','replay','work','head','receipt','swap'])for(const [label,mkStore,source,action,key] of [['transfer',o=>mk(transferScenario,OWNER,o),transferSource,'pay',owner],['repay',o=>mkRepay(repayScenario,o),repaySource,'repay_loan',payer]])
 test(`R13 fault at write step ${step} (${label}) leaves state, digest and registry unchanged; clean retry commits`,async()=>{
  let armed=true;const store=mkStore({faultHook:s=>{if(armed&&s===step)throw new Error('injected');}}),before=store.snapshot(),a=await signed(store,source,action,key);
  const r=await settle(store,source,action,a.text);assert.equal(r.status,'Rejected');assert.equal(r.code,'ATOMIC_COMMIT_FAULT');assert.equal(r.stateChanged,false);
  unchanged(store,before);assert.equal(digestOf(store),before.stateDigest);
  armed=false;assert.equal((await settle(store,source,action,a.text,before.stateDigest)).status,'LocalCommitted');
 });
test('fault hook can only abort: its return value never admits a refused request',async()=>{
 const store=mk(transferScenario,[bind('B1','Owner',owner,{revokedFromRound:'0'})],{faultHook:()=>({ok:true,signatureValid:true})}),before=store.snapshot(),a=await signed(store,transferSource,'pay'),r=await settle(store,transferSource,'pay',a.text);
 assert.equal(r.code,'AUTH_REVOKED');unchanged(store,before);
});
test('R12 ack loss: retry with the pre-commit expected digest is AlreadyCommitted and changes nothing; different statement is not',async()=>{
 const store=mk(),d0=digestOf(store),a=await signed(store,transferSource,'pay'),first=await settle(store,transferSource,'pay',a.text,d0);assert.equal(first.status,'LocalCommitted');
 const before=store.snapshot(),again=await settle(store,transferSource,'pay',a.text,d0);
 assert.equal(again.status,'AlreadyCommitted');assert.equal(again.head,first.head);assert.equal(again.replayKey,KEY);assert.equal(again.stateDigest,before.stateDigest);assert.equal(again.bindingId,'B1');unchanged(store,before);
 const fresh=await settle(store,transferSource,'pay',a.text);assert.equal(fresh.status,'AlreadyCommitted');unchanged(store,before);
 const art=JSON.parse(a.text),bad=json({...art,signatureHex:(art.signatureHex.startsWith('01')?'02':'01')+art.signatureHex.slice(2)});
 const forged=await settle(store,transferSource,'pay',bad,d0);assert.equal(forged.status,'Rejected');assert.equal(forged.code,'SIGNATURE_INVALID');unchanged(store,before);
 const other=transferSource.replace('const price: Qty<USD> = 10.00 USD;','const price: Qty<USD> = 9.00 USD;'),c=await signed(store,other,'pay');
 for(const dg of [d0,before.stateDigest]){const r=await settle(store,other,'pay',c.text,dg);assert.equal(r.status,'Rejected');assert.notEqual(r.status,'AlreadyCommitted');assert.equal(r.code,dg===d0?'ATOMIC_STALE_STATE':'S0_HISTORY_STALE');unchanged(store,before);}
 await store.revoke({bindingId:'B1'});const afterRevoke=await settle(store,transferSource,'pay',a.text,d0);assert.equal(afterRevoke.status,'AlreadyCommitted');
});
// R14: repayment accrual state across prepare/commit races.
test('R14 repay: a competing repayment changes accrual after prepare; stale loser has no partial effect; chained repay uses accrued state',async()=>{
 const store=mkRepay(),src1=fixtures[2][1],a=await signed(store,src1,'repay_loan',payer),src2=nonce(repaySource,'n2'),b=await signed(store,src2,'repay_loan',payer),d0=digestOf(store);
 const rs=await Promise.all([settle(store,src1,'repay_loan',a.text,d0),settle(store,src2,'repay_loan',b.text,d0)]);
 const winner=rs.find(r=>r.status==='LocalCommitted'),loser=rs.find(r=>r.status==='Rejected');assert.ok(winner&&loser,json(rs));assert.equal(loser.code,'ATOMIC_STALE_STATE');
 const ob=store.snapshot().state.obligations[0];
 assert.deepEqual(ob,winner===rs[0]?{id:'Loan',debtor:'Payer',creditor:'Creditor',asset:'A',principal:'100000',accrued:'500',outstanding:'100500',status:'Outstanding'}:{id:'Loan',debtor:'Payer',creditor:'Creditor',asset:'A',principal:'98000',accrued:'0',outstanding:'98000',status:'Outstanding'});
});
test('repay chain: 500 then 3000 follows accrual-first from the stored obligation, and settlement refuses a further S0 repay',async()=>{
 const store=mkRepay(),s1=fixtures[2][1],a=await signed(store,s1,'repay_loan',payer),r1=await settle(store,s1,'repay_loan',a.text);assert.equal(r1.status,'LocalCommitted');
 const s2=preHead(nonce(repaySource,'n2'),r1.head),b=await signed(store,s2,'repay_loan',payer),r2=await settle(store,s2,'repay_loan',b.text);assert.equal(r2.status,'LocalCommitted',json(r2));
 const st=store.snapshot().state;
 assert.deepEqual(st.obligations[0],{id:'Loan',debtor:'Payer',creditor:'Creditor',asset:'A',principal:'97500',accrued:'0',outstanding:'97500',status:'Outstanding'});
 assert.deepEqual(st.balances,[{account:'Payer',amount:'196500'},{account:'Creditor',amount:'3500'}]);assert.deepEqual(st.allowances,[{owner:'Payer',remaining:'196500',spent:'3500'}]);
 assert.equal(st.workRemaining,'8');assert.equal(st.workSpent,'2');assert.equal(st.head,r2.head);assert.deepEqual(st.consumedReplay,[PKEY,'["Midnight","Payer","n2"]']);
 assert.equal(store.snapshot().predecessor,r1.head);
 const s3=preHead(nonce(repaySource.replace('const amount = 30.00 USD;','const amount = 975.00 USD;'),'n3'),r2.head),c=await signed(store,s3,'repay_loan',payer),r3=await settle(store,s3,'repay_loan',c.text);assert.equal(r3.status,'LocalCommitted',json(r3));
 assert.equal(store.snapshot().state.obligations[0].status,'Settled');const before=store.snapshot();
 const s4=preHead(nonce(repaySource,'n4'),r3.head),d=await signed(store,s4,'repay_loan',payer),r4=await settle(store,s4,'repay_loan',d.text);assert.equal(r4.status,'Rejected');assert.equal(r4.layer,'core');assert.equal(r4.code,'S0_STAGE_UNSUPPORTED');unchanged(store,before);
});
test('transfer chain: second intent signs the derived head; stale digest from before the first commit is refused with no partial effect',async()=>{
 const store=mk(),d0=digestOf(store),a=await signed(store,transferSource,'pay'),r1=await settle(store,transferSource,'pay',a.text,d0);assert.equal(r1.status,'LocalCommitted');
 const s2=preHead(nonce(transferSource,'n2'),r1.head),b=await signed(store,s2,'pay'),before=store.snapshot();
 const stale=await settle(store,s2,'pay',b.text,d0);assert.equal(stale.code,'ATOMIC_STALE_STATE');unchanged(store,before);
 const r2=await settle(store,s2,'pay',b.text);assert.equal(r2.status,'LocalCommitted',json(r2));
 const st=store.snapshot().state;assert.deepEqual(st.balances,[{account:'Owner',amount:'7980'},{account:'Recipient',amount:'2000'},{account:'Fee',amount:'20'}]);
 assert.deepEqual(st.allowances,[{owner:'Owner',remaining:'7980',spent:'2020'}]);assert.equal(st.workRemaining,'8');assert.equal(st.workSpent,'2');
 assert.equal(r2.head,head(NET,r1.head,b.prepared.frame_sha256,r2.effects.slice(0,-1)));assert.notEqual(r2.head,r1.head);
});
test('changed state between snapshot and settle: every changed cell invalidates the expected digest',async()=>{
 for(const [label,change] of [['balance',{balances:[{account:'Owner',amount:'10001'},{account:'Recipient',amount:'0'},{account:'Fee',amount:'0'}]}],['fee cell',{balances:[{account:'Owner',amount:'10000'},{account:'Recipient',amount:'0'},{account:'Fee',amount:'5'}]}],['allowance',{allowance:{owner:'Owner',remaining:'9999',spent:'0'}}],['work',{work_remaining:'9'}]]){
  const a=mk(),b=mk({...transferScenario,...change}),{text}=await signed(a,transferSource,'pay'),before=b.snapshot();
  const r=await b.settle(req(b,transferSource,'pay',text,digestOf(a)));seen.push(json(r));assert.equal(r.code,'ATOMIC_STALE_STATE',label);unchanged(b,before);
 }
});
// R15/R16: head and candidate validation of the exact derived successor.
test('deriveSuccessorHead is deterministic, domain-separated and bound to frame, preHead, domain and every effect field',()=>{
 const eff=[{kind:'Debit',account:'Owner',asset:'A',amount:'1010'},{kind:'UseReplay',key:KEY}],f='ab'.repeat(32),h=deriveSuccessorHead(NET,'h0',f,eff);
 assert.equal(h,head(NET,'h0',f,eff));assert.match(h,/^[a-f0-9]{64}$/);assert.equal(h,deriveSuccessorHead(NET,'h0',f,structuredClone(eff)));
 assert.equal(h,deriveSuccessorHead(NET,'h0',f,[{asset:'A',kind:'Debit',amount:'1010',account:'Owner'},{key:KEY,kind:'UseReplay'}]));
 const variants=[deriveSuccessorHead({...NET,network:'mainnet'},'h0',f,eff),deriveSuccessorHead({...NET,chain:'x'},'h0',f,eff),deriveSuccessorHead({...NET,id:'X'},'h0',f,eff),deriveSuccessorHead(NET,'h1',f,eff),deriveSuccessorHead(NET,'h0','cd'.repeat(32),eff),
  deriveSuccessorHead(NET,'h0',f,[{...eff[0],amount:'1011'},eff[1]]),deriveSuccessorHead(NET,'h0',f,[eff[1],eff[0]]),deriveSuccessorHead(NET,'h0',f,[eff[0]])];
 assert.equal(new Set([h,...variants]).size,variants.length+1);
 assert.notEqual(h,createHash('sha256').update(canon({domain:NET,effects:eff,frameSha256:f,preHead:'h0'})).digest('hex'));
 assert.throws(()=>deriveSuccessorHead(NET,'h0','not-hex',eff),{code:'ATOMIC_INPUT_SCHEMA'});
});
test('R15/R16 validateSuccessor accepts only the exact derived head and untampered complete effects',()=>{
 const frame='ab'.repeat(32),fin=[{kind:'Debit',account:'Owner',asset:'A',amount:'1010'},{kind:'Credit',account:'Recipient',asset:'A',amount:'1010'},{kind:'UseAllowance',owner:'Owner',amount:'1010'},{kind:'UseReplay',key:KEY}];
 const h=head(NET,'h0',frame,fin),eff=[...fin,{kind:'AdvanceHead',predecessor:'h0',successor:h}],post={head:h};
 assert.doesNotThrow(()=>validateSuccessor(NET,'h0',frame,{effects:eff,candidatePost:post}));
 const code=(effects,candidatePost=post,pre='h0',f=frame)=>{try{validateSuccessor(NET,pre,f,{effects,candidatePost});return 'accepted';}catch(e){return e.code;}};
 assert.equal(code([...fin,{kind:'AdvanceHead',predecessor:'h0',successor:'solver-chosen'}],{head:'solver-chosen'}),'ATOMIC_HEAD_NOT_DERIVED');
 assert.equal(code(eff,{head:'other'}),'ATOMIC_HEAD_NOT_DERIVED');
 assert.equal(code([...fin,{kind:'AdvanceHead',predecessor:'hX',successor:h}]),'ATOMIC_HEAD_NOT_DERIVED');
 assert.equal(code([{...fin[0],amount:'1011'},...fin.slice(1),eff[4]]),'ATOMIC_HEAD_NOT_DERIVED');
 assert.equal(code([fin[0],...fin.slice(1),{kind:'Credit',account:'Fee',asset:'A',amount:'0'},eff[4]]),'ATOMIC_HEAD_NOT_DERIVED');
 assert.equal(code(fin),'ATOMIC_HEAD_NOT_DERIVED');
 assert.equal(code([eff[4],...fin]),'ATOMIC_HEAD_NOT_DERIVED');
 assert.equal(code([...eff,eff[4]]),'ATOMIC_HEAD_NOT_DERIVED');
 assert.equal(code(eff,post,'h0','cd'.repeat(32)),'ATOMIC_HEAD_NOT_DERIVED');
 assert.equal(code([],post),'ATOMIC_HEAD_NOT_DERIVED');
 assert.equal(code(eff,undefined,'hX'),'ATOMIC_HEAD_NOT_DERIVED');
});
test('no result, snapshot or error ever claims ledger or external authority qualification',()=>{
 assert.ok(seen.length>20);
 for(const text of seen){
  assert.doesNotMatch(text,/Authenticated|LedgerCommitted|"status":"Accepted"|"ledger_accepted":true|"authority_valid":true/);
  const r=JSON.parse(text);assert.equal(r.ledger_accepted,false);assert.equal(r.authority_valid,null);assert.equal(r.qualification,'local-stipulation');
 }
});
