import fs from 'node:fs';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';
const root='/home/charl/Moriarty/.worktrees/source-defined-repayment', out='/home/charl/Moriarty/deliverables/source-defined-repayment-2026-09-11/audit-02';
const base=root+'/experiments/moriarty-language/', ex=base+'spec/successor/examples/';
const {createFinancialAgreementSourceV1}=await import(base+'src/successor/financial-agreement-source-v1.ts');
const {formatFinancialAgreementSource}=await import(base+'src/successor/financial-agreement-source-frontend.ts');
const {createFundedFinancialExpressionSourceV1}=await import(base+'src/successor/funded-expression-source-v1.ts');
const {canonical}=await import(base+'src/successor/expression-wire-v1.ts');
const read=n=>fs.readFileSync(ex+n,'utf8');const source=read('source-defined-payment.mori'), snap=read('expression-funded-payment.snapshots.json'), state=read('expression-funded-payment.state.json'), old=read('expression-funded-payment.mori'), schema=read('expression-funded-payment.schema.json');
const api=createFinancialAgreementSourceV1(), results=[];
function check(name,fn){fn();results.push(name)}
function reject(r){assert.equal(r.status,'Rejected',JSON.stringify(r));for(const k of ['post','financialPost','effects','descriptors','result'])assert.ok(!(k in r));return r}
const good=api.evaluate(source,snap,state);
check('baseline and canonical schema',()=>{assert.equal(good.status,'FundedExpressionPrepared');assert.deepEqual(good,createFundedFinancialExpressionSourceV1(schema).evaluate(old,snap,state));assert.equal(canonical(api.elaborate(source).schema),schema)});
check('formatter stable and equivalent',()=>{const f=formatFinancialAgreementSource(source);assert.equal(formatFinancialAgreementSource(f),f);assert.deepEqual(api.evaluate(f,snap,state),good)});
for(const [name,from,to,needle] of [
 ['reserved state','state paid: UInt128;','state some: UInt128;','state some: UInt128;'],['reserved param','first: Quantity','none: Quantity','none: Quantity'],
 ['operation selfcycle','payer: Text;','payer: Operation<Repay>;','Operation<Repay>'],['nested operation cycle','payer: Text;','payer: Option<Collection<Operation<Repay>,1>>;','Operation<Repay>'],
 ['nested missing asset','state paid: UInt128;','state paid: Option<Collection<Amount<Missing>,1>>;','Missing'],['unknown parameter','first: Quantity<Units<Cash,1>,0>','first: Option<Record<Missing>>','Missing'],
 ['missing repay field','payer: Text;','','record RepayFields'],['extra repay field','payer: Text;','payer: Text; extra: Text;','extra: Text;'],['bad repay type','payer: Text;','payer: UInt128;','payer: UInt128;']
])check(name,()=>{assert.ok(source.includes(from));const s='/* 😀é */\n'+source.replace(from,to),r=reject(api.check(s));assert.equal(r.span.kind,'source');assert.ok(Buffer.from(s).subarray(+r.span.start,+r.span.end).toString().includes(needle),JSON.stringify(r));assert.deepEqual(api.evaluate(s,'invalid','invalid'),r)});
for(const name of ['constructor','toString','hasOwnProperty','valueOf'])check('prototype ordinary '+name,()=>{const s=source.replace('state paid: UInt128;',`state paid: UInt128; state ${name}: UInt128;`),sn=JSON.parse(snap);sn.Pre[name]='8';const r=api.evaluate(s,canonical(sn),state);assert.equal(r.status,'FundedExpressionPrepared',JSON.stringify(r));assert.equal(r.post[name],'8')});
for(const [name,mutate] of [['allowance',s=>s.allowances[0].remaining='1'],['history',s=>s.usedTransferIds.push('T1')],['nominal unit',s=>s.obligations[0].denomination='USD'],['invalid invariant',s=>s.obligations[0].outstanding='99'],['unknown state field',s=>s.extra='1'],['work mismatch',s=>s.work.remaining='99'],['closure reserve overflow',s=>s.work.closureReserve=(2n**128n-1n).toString()]])check(name,()=>{const st=JSON.parse(state);mutate(st);reject(api.evaluate(source,snap,JSON.stringify(st)))});
for(const [name,a,b] of [['guard','requires pre.due > 0;','requires false;'],['ensure','ensures post.paid == pre.paid + payment;','ensures false;'],['wrong settlement','settlementAsset: "Cash"','settlementAsset: "USD"'],['financial post read','post.paid','post.obligations']])check(name,()=>{assert.ok(source.includes(a));reject(api.evaluate(source.replace(a,b),snap,state))});
check('exact expression plus actions work',()=>{const cost=BigInt(JSON.parse(snap).workInitial)-BigInt(good.workRemaining);for(const d of [0n,-1n]){const sn=JSON.parse(snap),st=JSON.parse(state);sn.workInitial=st.work.remaining=String(cost+d);const r=api.evaluate(source,canonical(sn),JSON.stringify(st));if(d===0n){assert.equal(r.status,'FundedExpressionPrepared');assert.equal(r.workRemaining,'0');assert.equal(r.financialPost.work.closureReserve,st.work.closureReserve)}else reject(r)}});
check('ordinary financial-looking field cannot replace projection',()=>{const s=source.replace('state paid: UInt128;','state paid: UInt128; state obligations: UInt128;').replace('next.paid =','next.obligations = 0; next.paid ='),sn=JSON.parse(snap);sn.Pre.obligations='100';const r=api.evaluate(s,canonical(sn),state);assert.equal(r.post.obligations,'0');assert.equal(r.financialPost.obligations[0].principal,'70')});
check('returned core/schema mutation no bypass',()=>{const e=api.elaborate(source);e.core.statements=[];e.schema.operations={};assert.deepEqual(api.evaluate(source,snap,state),good);reject(api.evaluate(e,snap,state))});
for(const input of [null,{},new String(source),42])check('source primitive '+typeof input,()=>reject(api.evaluate(input,snap,state)));
check('no hostile accessors',()=>{const x={get workInitial(){throw Error('touched')}};reject(api.evaluate(source,x,state));reject(api.evaluate(source,snap,x))});
for(const [name,sn,st] of [['snapshot bound',' '.repeat(2000001),state],['state bound',snap,' '.repeat(65537)],['snapshot whitespace',snap+' ',state],['snapshot missing pre','{"Args":{},"Obs":{},"workInitial":"100"}',state]])check(name,()=>reject(api.evaluate(source,sn,st)));
for(const n of [257])check('declaration limit',()=>reject(api.check(source.replace('unit Cash;',Array.from({length:n},(_,i)=>`unit U${i};`).join('')+'unit Cash;'))));
check('type depth bound',()=>reject(api.check(source.replace('state paid: UInt128;',`state paid: ${'Option<'.repeat(65)}UInt128${'>'.repeat(65)};`))));
function cli(name,args,expected){const r=spawnSync(process.execPath,[base+'src/cli.ts',...args],{encoding:'utf8'});fs.writeFileSync(out+'/cli-'+name+'.json',JSON.stringify(r,null,2));assert.equal(r.status,expected);if(expected===0)assert.equal(r.stderr,'');else assert.equal(r.stdout,'');return r}
const p=['--profile','moriarty-financial-agreement-source/1'];check('CLI check',()=>cli('check',['check',...p,ex+'source-defined-payment.mori'],0));check('CLI format',()=>assert.equal(cli('format',['format',...p,ex+'source-defined-payment.mori'],0).stdout,formatFinancialAgreementSource(source)));check('CLI simulate',()=>assert.deepEqual(JSON.parse(cli('simulate',['simulate',...p,'--snapshots',ex+'expression-funded-payment.snapshots.json','--repayment-state',ex+'expression-funded-payment.state.json',ex+'source-defined-payment.mori'],0).stdout).result,good));check('CLI schema disallowed',()=>cli('schema',['check',...p,'--schema',ex+'expression-funded-payment.schema.json',ex+'source-defined-payment.mori'],2));check('CLI original source diagnostic',()=>{const s='// 😀\n'+source.replace('payer: Text;','payer: Operation<Repay>;');fs.writeFileSync(out+'/cycle.mori',s);const r=JSON.parse(cli('cycle',['check',...p,out+'/cycle.mori'],1).stderr);assert.equal(r.span.kind,'source');assert.equal(Buffer.from(s).subarray(+r.span.start,+r.span.end).toString(),'Operation<Repay>')});
fs.writeFileSync(out+'/probe-results.json',JSON.stringify({passed:results.length,results},null,2));console.log(results.length+' independent probes passed');
