import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,existsSync,rmSync,statSync,symlinkSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {decodePreviewIndexedOwner} from './indexed-owner.mjs';
const api=await import('./preview-launch.mjs').catch(e=>{if(e.code==='ERR_MODULE_NOT_FOUND')return {};throw e;});
const publicIdentity=JSON.parse(readFileSync(new URL('../../../evidence/midnight-preview-2026-09-07/wallet-public.json',import.meta.url)));
const hash='11'.repeat(32),txId='00'+'22'.repeat(32);
const plan=()=>({schema:'moriarty.preview-financial-launch/1',kind:'loan',build:{receiptPath:'/synthetic/build.json',receiptSha256:hash,sourceManifestHash:hash},networkConfig:{networkId:'preview',node:'https://rpc.preview.midnight.network',indexer:'https://indexer.preview.midnight.network/api/v4/graphql',indexerWS:'wss://indexer.preview.midnight.network/api/v4/graphql/ws',proofServer:'http://127.0.0.1:16300'},wallet:{seedFile:publicIdentity.seedFile,stateDirectory:'/synthetic/original-preview-state',expectedAddress:publicIdentity.address},roles:{firstAddress:decodePreviewIndexedOwner(publicIdentity.address),secondAddress:'33'.repeat(32),secretsFile:'/synthetic/roles.json'},privateState:{directory:'/synthetic/new-store',passwordFile:'/synthetic/password'},networkTag:'3c096de209e06a1a8c52be7bda109ee8c891a42288c0a9db5495f9616dd13796',expectedProtocolVersion:1000000,limits:{allocationId:'sp05-preview-loan-01',deadlineMs:Date.now()+60000,submissions:4,dustFee:'1000000000000000',grossByLogicalAsset:{USD_TEST_ASSET:'20000000000'}},outputDirectory:'/synthetic/output'});
function result(){const x=JSON.parse(readFileSync(new URL('../../../deliverables/sp05-financial-integration-2026-09-09/local-continuation-02/run-public/integration-result.json',import.meta.url)));x.schema='moriarty.preview-financial-integration/1';x.status='FAILED';x.driver.schema='moriarty.preview-financial-run/1';return x;}
function temp(t){const dir=mkdtempSync(join(tmpdir(),'moriarty-preview-public-test-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));return dir;}
test('closed Preview plan validates existing public wallet identity without private reads',()=>{assert.equal(typeof api.validatePreviewLaunchPlan,'function');const p=plan();assert.deepEqual(api.validatePreviewLaunchPlan(p),p);assert.notEqual(api.validatePreviewLaunchPlan(p),p);});
test('Preview plan rejects wrong target, original identity changes, recovery fields, hidden values and unsafe overlap',()=>{assert.equal(typeof api.validatePreviewLaunchPlan,'function');for(const mutate of [p=>p.networkConfig.networkId='undeployed',p=>p.networkConfig.node='https://rpc.preview.midnight.network.evil/',p=>p.networkConfig.indexerWS='ws://indexer.preview.midnight.network/api/v4/graphql/ws',p=>p.networkConfig.proofServer='https://prover.example',p=>p.wallet.seedFile='/synthetic/new.seed',p=>p.wallet.expectedAddress='mn_addr_preview1wrong',p=>p.roles.firstAddress=hash,p=>p.roles.secondAddress=p.roles.firstAddress,p=>p.outputDirectory=p.wallet.stateDirectory+'/nested',p=>p.roles.secretsFile=p.outputDirectory+'/secrets',p=>p.limits.submissions=5,p=>p.limits.grossByLogicalAsset.EXTRA='0',p=>p.limits.dustFee='-1',p=>p.limits.deadlineMs=Date.now()-1,p=>p.sourceTestOnly=true,...['existingDeployment','existingInitializedLoan','existingInitializedSwap','existingStaleLoan','recoveryPlan','continuationPlan','adapters'].map(k=>p=>p[k]={}),p=>Object.defineProperty(p,'secret',{value:'NEVER_PUBLIC'}),p=>Object.defineProperty(p.networkConfig,'node',{get(){throw Error('GETTER_RAN');},enumerable:true})]){const p=plan();mutate(p);assert.throws(()=>api.validatePreviewLaunchPlan(p));};});
test('actual retained full observations and66-hex SDK identifiers survive durable Preview result writer',t=>{assert.equal(typeof api.retainPreviewIntegrationResult,'function');const dir=temp(t),x=result();api.retainPreviewIntegrationResult(dir,x);const raw=readFileSync(join(dir,'integration-result.json'),'utf8'),saved=JSON.parse(raw);assert.equal(saved.driver.transactionIds[0].length,66);assert.deepEqual(saved.driver.stages,x.driver.stages);assert.deepEqual(saved.comparisons,x.comparisons);assert.equal(saved.financialAcceptance,false);assert.equal(statSync(join(dir,'integration-result.json')).mode&0o777,0o600);assert.throws(()=>api.retainPreviewIntegrationResult(dir,x));});
test('failed preflight result preserves undefined optional fields without private SDK data',t=>{assert.equal(typeof api.retainPreviewIntegrationResult,'function');const dir=temp(t);api.retainPreviewIntegrationResult(dir,{schema:'moriarty.preview-financial-integration/1',status:'FAILED',kind:'loan',sourceTestOnly:false,networkAcceptance:false,proofAcceptance:false,financialAcceptance:false,build:undefined,assetBindings:undefined,phase:'preflight',driver:undefined,cleanup:{walletStopped:true,pendingOperations:0,containmentComplete:false},setupPendingOperations:0,comparisons:[],financialComparison:undefined,failureCode:'PREVIEW_GENESIS_MISMATCH',scope:'Fixed Preview composition; only independently reviewed actual evidence establishes financial acceptance'});assert.equal(JSON.parse(readFileSync(join(dir,'integration-result.json'))).failureCode,'PREVIEW_GENESIS_MISMATCH');});
test('private nested fields, accessors, symbols, arbitrary errors and wrong identifier/hash lengths never write',t=>{assert.equal(typeof api.retainPreviewIntegrationResult,'function');const dir=temp(t);for(const mutate of [x=>x.roles={firstSecret:hash},x=>x.driver.cleanup.secret='NEVER_PUBLIC',x=>x.driver.stages[0].transaction.inputs.push({privateWitness:'NEVER_PUBLIC'}),x=>x.comparisons[0].publicState.password='NEVER_PUBLIC',x=>x.failureCode='NEVER_PUBLIC',x=>x.scope='NEVER_PUBLIC',x=>x.driver.transactionIds[0]='a'.repeat(65),x=>x.driver.stages[0].transaction.transactionHash=txId,x=>x.driver[Symbol('private')]='NEVER_PUBLIC',x=>Object.defineProperty(x.driver,'stages',{get(){throw Error('GETTER_RAN');},enumerable:true}),x=>Object.defineProperty(x.driver.cleanup,'hidden',{value:'NEVER_PUBLIC'}),x=>x.driver.cleanup.toJSON=()=>({secret:'NEVER_PUBLIC'})]){const x=result();mutate(x);assert.throws(()=>api.retainPreviewIntegrationResult(dir,x));assert.equal(existsSync(join(dir,'integration-result.json')),false);}});
test('stage/event retain actual identifiers and reject symlink destinations',t=>{assert.equal(typeof api.retainPreviewStage,'function');const dir=temp(t),s=result().comparisons[0];assert.deepEqual(api.retainPreviewStage(dir,s),{status:'RECORDED',stage:s.stage,txId:s.txId});assert.throws(()=>api.retainPreviewStage(dir,s));assert.deepEqual(api.publicPreviewLaunchEvent({kind:'submitted',txId,identifiers:[txId],transactionHash:hash}),{kind:'submitted',txId,identifiers:[txId],transactionHash:hash});const target=temp(t);symlinkSync(target,join(dir,'linked'));assert.throws(()=>api.retainPreviewIntegrationResult(join(dir,'linked'),result()));});
export {plan as previewPlanFixture};
test('array accessors never run while projecting public evidence or events',t=>{const dir=temp(t);for(const kind of ['result','event']){let touched=false;const ids=[txId];Object.defineProperty(ids,'0',{get(){touched=true;return txId;},enumerable:true});if(kind==='result'){const r=result();r.driver.transactionIds=ids;assert.throws(()=>api.retainPreviewIntegrationResult(dir,r));}else assert.throws(()=>api.publicPreviewLaunchEvent({kind:'submitted',txId,identifiers:ids,transactionHash:hash}));assert.equal(touched,false);}});
test('actual stopped provider event operation text is omitted from public projection',()=>{const out=api.publicPreviewLaunchEvent({kind:'stopped',operation:'NEVER_PUBLIC',identifiers:[txId],reservationRetained:true,pendingOperations:1});assert.deepEqual(out,{kind:'stopped',identifiers:[txId],reservationRetained:true,pendingOperations:1});});
test('nested acceptance claims cannot be promoted by public writer',t=>{const dir=temp(t),r=result();r.financialComparison.proofAcceptance=true;assert.throws(()=>api.retainPreviewIntegrationResult(dir,r));assert.equal(existsSync(join(dir,'integration-result.json')),false);});
