# Historical draft assembly script; do not rerun over the converged synthesis.
# Final panel amendments are maintained in report/features/graph and CONVERGENCE.md.
from pathlib import Path
import json,hashlib,csv,datetime
D=Path('deliverables/language-design-2026-09-09');R=Path('raw/sources/language-design-2026-09-09');base=Path.cwd()
def dump(p,x):p.write_text(json.dumps(x,indent=2,ensure_ascii=False)+'\n')
def rel(x):
 s=str(x);return s[len(str(base))+1:] if s.startswith(str(base)+'/') else s
us=json.loads((R/'usability/source-inventory.json').read_text());ss=json.loads((D/'semantics-claims.json').read_text())
sources=[]
for x in us['sources']+ss['sources']:
 x=dict(x)
 for k,v in list(x.items()):
  if isinstance(v,str):x[k]=rel(v)
 x['node_type']='source';x['observation_window']='2026-09-09 UTC; historical academic edition identified in record';sources.append(x)
for p in sorted((R/'official').glob('D*.json')):
 x=json.loads(p.read_text())
 if 'supersedes_extraction_only' in x:continue
 x['node_type']='source';x['source_id']=x['id'];x['receipt']=str(p)
 if x['id'] in ['D06','D07','D08','D09','D10']:
  correction=json.loads(p.with_name(p.stem+'-body.json').read_text());x['preferred_text_path']=correction['text_path'];x['preferred_text_sha256']=correction['text_sha256'];x['extraction_correction']=str(p.with_name(p.stem+'-body.json'))
 if x['id']=='D04':x['coverage']='Initial static shell; no readable article; use D04R'
 sources.append(x)
repo_paths={'R1':'deliverables/defi-language-design-2026-09-07/LANGUAGE-DESIGN.md','R2':'experiments/moriarty-language/spec/successor/README.md','R3':'ROADMAP.md','R4':'deliverables/defi-report8-comparison-2026-09-09/ROADMAP-REMAINING.md','R5':'deliverables/erc4626-vault-report-2026-09-08/DESIGN-IMPLICATIONS.md'}
for sid,p in repo_paths.items():sources.append({'id':sid,'node_type':'source','source_kind':'repository observation','path':p,'title':p,'sha256':hashlib.sha256(Path(p).read_bytes()).hexdigest(),'version':'base9157a29; checked path content at dossier assembly','scope':'repository design/status, not independent external evidence'})
pins=[]
for p in sorted((R/'official').glob('pin-*.json')):
 x=json.loads(p.read_text());ls=x['stdout'].splitlines();x['default_branch']=next(a.split()[1].removeprefix('refs/heads/') for a in ls if a.startswith('ref:'));x['commit']=next(a.split()[0] for a in ls if not a.startswith('ref:'));pins.append(x)
dump(D/'repository-pins.json',pins)
dump(D/'source-manifest.json',{'schema':'moriarty.language-design.source-manifest/1','lifecycle':'S2','observation_window':'2026-09-09 UTC','academic_full_works':13,'academic_independence_note':'Elm2012/2013 share lineage; primary document count is not independent replication count','sources':sources,'unavailable_attempts':us['unavailable_attempts']+[{'receipt':str(R/'semantics/S02-access-failure.json'),'status':'DNS unavailable; not counted as read'}]})
# Standalone rows hold decisions, safety cost, gap and independently specified tests.
rows=[
('F01','adapt','TypeScript-style external .mori','Recognize declarations and records','UCL02 UCL15','R1 R2 D11','Familiar punctuation can imply wrong host semantics; state exact grammar/profile','Syntax-only profile exists; TS alignment and full semantics open','action pay(paid: Amount<USD>) { ... }','Compare clause meaning and repairs across experience groups; reject host JS expressions','medium'),
('F02','defer','Inert TypeScript tagged template','Embed canonical source in TS build without callbacks','UCL17','R2 D11','No interpolation or runtime AST escape; bytes and source maps must preserve bounds','No admitted embedding or source-map contract','moriarty.source`action pay(...) { ... }`','Template and file yield identical Core; reject interpolation and oversized source before evaluation','medium'),
('F03','reject','Unrestricted TS runtime in contracts','Keep execution and proving finite','SEM-04-L','D11 R1','No closures, eval, ambient IO, host coercions or dynamic imports in trusted execution','Host witness boundary needs explicit validation','Date.now(); await fetch(url); // excluded','Reject ambient clock/IO and arbitrary callback at source boundary','high'),
('F04','adopt','Explicit public financial types','See asset, amount, share and duty roles','UCL08 UCL15','D10 D14 R5','Nominal units/identities; arithmetic checks additional to type checking','Types parse; full successor checker and nominal binding open','paid: Amount<USD>','Wrong asset/share payment rejects; valid same-unit payment preserves allocation','high'),
('F05','adapt','Local inference with visible inferred types','Reduce repeated annotations while preserving meaning','UCL08','D08 R1','No any/unsafe cast; inferred bounds and effects remain inspectable','Local static inference not implemented','let remaining = pre.outstanding - paid;','Explicit/inferred variants same Core; ambiguous units reject; developer repair study','medium'),
('F06','adopt','Pure pre-state and staged updates','Predict all changes before acceptance','SEM-01-R UCL17','D01 D02 R1','No reading tentative next; failure atomicity; ordered diagnostic/effect policy','Proposal/parsing exists; full typed execution remains open','next.outstanding = remaining;','Later guard failure discards tentative state/effects; remaining debt retained','high'),
('F07','adapt','Closed typed effects separate from authority','Inspect what an action proposes and permits','SEM-04-R','D08 R1','Effect membership is not spend permission; bind concrete complete effects','Successor effect typing and authority integration open','emit Transfer { asset: usd, amount: paid, ... };','Right effect but wrong recipient or excess gross debit rejects','high'),
('F08','defer','General resumable effect handlers','Avoid hidden multiplicity in financial code','SEM-04-L UCL06','D08 R1','Multiple resume can duplicate effects/work; single-shot/accounting theorem needed','No financial handler calculus or admitted use case','handle payment with customHandler; // deferred','Any future handler cannot duplicate nonce, payment or duty; bounded invocation proof','high'),
('F09','adapt','Finite event inputs and schedules','Express delayed financial actions explicitly','SEM-01-L SEM-02-L','D03 D04R R1','Bound queue, horizon, observations, ordering and recovery reserve','No successor schedule/observation declaration semantics','on PaymentDue(due: DueObservation) { ... } // proposed','Out-of-order duplicate/stale observation rejected by explicit policy; overflow preserves duty','medium'),
('F10','reject','Infinite streams or implicit lifetime reset','Preserve finite admitted financial work','SEM-01-L SEM-02-L','R1','Productivity/causality not finite lifetime; no unbounded queue or allowance refresh','Lifecycle work conservation still open','subscribe forever; // excluded','Sequence exhausting allowance cannot regain it via continuation/split/join','high'),
('F11','adopt','Explicit residual duties and recovery','Know what remains owed after progress','UCL06 SEM-06-L','R1 R5','No duty discard through timeout/cancel/rename; reserve bounded recovery work','Partial financial utilities exist; general residual semantics open','next.outstanding = remaining;','Partial payment plus expiry retains unpaid duty or authorized resolution','high'),
('F12','adopt','Checked arithmetic and named rounding','Understand token/share conversion outcomes','UCL15','R1 R5 D11','Intermediate bounds, scale, zero division and rejection explicit','Some atomic operations; successor rounding names merely parse','floor_div(numerator, denominator)','Zero divisor/range overflow reject; opposite rounding changes expected share result','high'),
('F13','adapt','Structured source diagnostics','Repair underlying financial mistake','UCL11','R2','No unsafe repair suggestions or private witness disclosure; truthful stage status','Syntax codes exist; semantic/proof/ledger diagnostics open','UNIT_MISMATCH: Expected Amount<USD>; found Shares<V>','Measure interpretation and correct next edit separately; no duty-erasing workaround','medium'),
('F14','adapt','Content-addressed typed Core and dependencies','Identify exact program and dependency closure','SEM-03-R UCL20','D06 D07 D14','Full refs/domain separation/nominal IDs; hash not equivalence or authority','No frozen successor Core encoding or semantic identity','dependencies: BoundedList<FullDefinitionRef>','Rename-only and changed dependency have specified different identity behavior','medium'),
('F15','adopt','Separate source/build/artifact/claim identities','Understand what was reviewed, built and proved','SEM-03-L SEM-05-R','R1 D11','Hash complete immediate inputs; proof context/state/authority separate from code','Source hashes exist; complete cross-layer commitment contract open','{ sourceDigest, coreDigest, semanticProfile }','Change compiler/profile/verifier/observation; stale cached proof cannot admit new statement','high'),
('F16','defer','Unison-style database as primary editor workflow','Keep ordinary source review available first','UCL17 UCL20','D09 D12 D13','Storage/authorship/license/recovery cost; empirical benefit untested','Text workflow already exists; no demonstrated need for replacement','import { quote } from pinnedLibrary; // future syntax','Future workflow must export complete reviewable source/provenance and handle upgrades','medium'),
('F17','adopt','Explicit version and migration review','Prevent silent reinterpretation of live duties','SEM-03-L','D12 D14 R1 R5','Retain old program, claim lineage, nominal identity and authorized migration','No general private/live obligation migration acceptance','migrate oldRef to newRef under authority; // proposed','Alias update cannot change prior obligation; authorized migration conserves duties/work','high'),
('F18','adopt','Separate preparation from proof and settlement','Know whether an action actually happened','SEM-01-R','D02 D05 R3','Four mandatory claims plus native/ledger checks; no verified badge from parsing','Partial status flows; full financial acceptance remains open','{ tag: "Prepared", effects, duties, authority, work }','Well-typed/signed proposal with missing mandatory proof fails closed before acceptance','high'),
('F19','adopt','Human task evaluation before usability claims','Verify understandable authoring and repair','UCL19 UCL22','R3','Expert PL votes are design review, not participant evidence','No developer study reproduced here','Compare partial-payment comprehension tasks','Preregister correctness/time/repair/timeout; stratify experience; retain null outcomes','high'),
('F20','adopt','Profile-specific grammar and correspondence checks','Keep published syntax and tools consistent','UCL17','R1 R2','Lexing/parsing/formatting separate from typing; stable spans and profile labels','Bounded syntax checks exist; semantic/Core/K/Compact correspondence open','check-syntax versus check versus prove','Grammar/lexer/parser/formatter/docs agree; formatter preserves AST, later all-layer financial observations','high')]
features=[]
for i,disp,title,purpose,claims,src,safety,gap,example,test,confidence in rows:
 features.append({'id':i,'node_type':'feature','disposition':disp,'title':title,'user_visible_purpose':purpose,'claim_ids':claims.split(),'source_ids':src.split(),'tradeoff_and_finite_resource_safety':safety,'current_moriarty_gap':gap,'typescript_style_example':example,'minimal_acceptance_test':test,'confidence':confidence,'status':'PROVISIONAL S2','test_status':'specified-only; not executed'})
dump(D/'features.json',features)
with (D/'feature-matrix.csv').open('w') as f:
 w=csv.DictWriter(f,fieldnames=list(features[0]),lineterminator="\n");w.writeheader();w.writerows({k:('; '.join(v) if isinstance(v,list) else v) for k,v in x.items()} for x in features)
lines=['# Provisional feature checklist','', 'All rows are S2 recommendations for PL review. Adopt means retain a design requirement, not implemented or accepted behavior. Every test below is specified-only. Confidence concerns the bounded recommendation, not a measured usability benefit. Detailed safety, gaps and syntax examples are in [feature-matrix.csv](feature-matrix.csv) and [features.json](features.json).','','| ID | Position | Feature and user purpose | Minimum distinguishing acceptance test |','|---|---|---|---|']
for x in features:lines.append(f"| {x['id']} | {x['disposition']} | **{x['title']}** — {x['user_visible_purpose']} | {x['minimal_acceptance_test']} |")
lines+=['','Initial path: F01 external `.mori` with familiar declarations; F02 inert tagged-template/build-time integration deferred; F03 unrestricted TypeScript execution excluded. F06/F11/F18 preserve pure preparation, residual duties and mandatory acceptance. F14/F15 add identity discipline only after typed Core has a defined encoding. No database/editor replacement is required to start SP02.','','## Review decisions still open','','Confirm the smallest embedding scope; choose public annotation requirements; decide if finite actions/schedules suffice without reactive syntax; specify hash domains and nominal identity. The three-PL review may revise these positions. Human accessibility remains unmeasured.']
(D/'FEATURE-CHECKLIST.md').write_text('\n'.join(lines)+'\n')
# Normalize existing claim vocabularies without changing their immutable source receipts.
claims=[]
for c in json.loads((D/'usability-claims.json').read_text())['claims']+ss['claims']:
 c=dict(c);c['node_type']='claim';c['kind']=c.get('kind',c.get('evidence_kind','')).replace(' ','_');claims.append(c)
official=[
('DOC01','D01 D02 D03 D04R','source_fact','Current Elm architecture uses Model/View/Update with commands/subscriptions; the May2016 Elm0.17 post replaces signals. Historical FRP papers do not specify current Elm.','D01 Basic Pattern; D02 element; D03 subscriptions; D04R Farewell to FRP'),
('DOC02','D06 D07','source_fact','Unison references terms/types by structural hashes and dependency hashes, with names separately stored; short prefixes require unambiguous environment resolution.','D06 opening technical explanation; D07 Literal Hash References and Short Hashes'),
('DOC03','D08','source_fact','Unison ability requirements are typechecked; handlers may ignore or multiply resume continuations.','Abilities in function types; Typechecking rule; Pattern matching on ability constructors'),
('DOC04','D10 D14','contradiction','Tutorial shorthand unique by name is qualified by reference: unique type identity incorporates generated UUID into the type hash. Financial nominal identity must be explicit rather than inferred from a mutable spelling.','D10 meaning of unique; D14 final paragraph'),
('DOC05','D11','source_fact','Compact documents TypeScript-like syntax together with bounded fixed-size data, bounded loops, prohibited recursion, explicit disclosure and separate runner witnesses.','Overview'),
('DOC06','D12 D13','source_fact','Unison documents guided dependent updates and separate author/license values associated with projects. Hash identity does not replace upgrade workflow or provenance metadata.','D12 update/upgrade workflows; D13 entire short guide'),
('DOC07','D09','source_fact','Unison tour describes a codebase workflow and caching pure watch results by expression hash. This is not evidence that a financial proof remains valid for changed state or verifier context.','Tour watch expressions/testing'),
('REPO01','R1 R2 R3 R4 R5','repository_observation','Successor syntax profile is provisional and does not supply typing, evaluation, K emission or financial admission; current design requires explicit authority, units, residual duties, bounds and all-layer correspondence.','R2 introduction and unsupported; R1 semantics and mandatory proof acceptance; R3 roadmap')]
for i,src,kind,stmt,loc in official:claims.append({'id':i,'node_type':'claim','kind':kind,'statement':stmt,'source_ids':src.split(),'source_locator':loc,'confidence':'high within source scope','lifecycle':'S2','acceptance_effect':'none'})
# Attach documentation facts to proposals for explicit source -> claim -> feature paths.
extra={'F01':['DOC05','REPO01'],'F02':['DOC05'],'F03':['DOC05'],'F04':['DOC04'],'F06':['DOC01','REPO01'],'F07':['DOC03'],'F08':['DOC03'],'F09':['DOC01'],'F11':['REPO01'],'F12':['DOC05','REPO01'],'F14':['DOC02','DOC04'],'F15':['DOC07'],'F16':['DOC06','DOC07'],'F17':['DOC06','DOC04'],'F18':['REPO01'],'F20':['REPO01']}
for f in features:f['claim_ids']+=extra.get(f['id'],[])
dump(D/'features.json',features)
edges=[]
for c in claims:
 for sid in c['source_ids']:edges.append({'source':sid,'target':c['id'],'type':'supports' if c['kind'] not in ['contradiction','open_question'] else 'qualifies','evidence':'inspected-source','locator':c.get('source_locator',c.get('locators'))})
for f in features:
 for cid in f['claim_ids']:edges.append({'source':cid,'target':f['id'],'type':'informs','evidence':'researcher-recommendation','status':'provisional'})
ids={x['id'] for x in sources+claims+features};assert all(e['source'] in ids and e['target'] in ids for e in edges)
dump(D/'research-graph.json',{'schema':'moriarty.language-design.graph/1','directed':True,'node_types':['source','claim','feature'],'edge_types':['supports','qualifies','informs'],'status':'S2 research; no accepted semantics inferred','nodes':sources+claims+features,'edges':edges})
md=['# Source, claim and feature graph','','The JSON contains typed, directed edges with source locators. `supports` is scoped evidence; `informs` is a provisional recommendation, not a proved implication. No opaque extraction service or graph database is required.','','```mermaid','flowchart LR','  U[Usability studies] --> UC[Task-specific findings and limits]','  E[Historical Elm and current docs] --> EC[Pure update plus explicit environment]','  T[Temporal/effect calculi] --> TC[Causality and effects differ from finite authority]','  N[Unison and reproducible builds] --> NC[Names, dependencies and identity contexts]','  UC --> F1[TS-style surface and tested diagnostics]','  EC --> F2[Bounded prepared transitions]','  TC --> F2','  NC --> F3[Versioned Core and artifact commitments]','  F1 --> G[Source/Core/K/Compact/ledger obligations stay open]','  F2 --> G','  F3 --> G','```','','## Traceable feature edges','','| Feature | Claim IDs | Original sources |','|---|---|---|']
byclaim={c['id']:c for c in claims}
for f in features:md.append('| '+f['id']+' '+f['title']+' | '+', '.join(f['claim_ids'])+' | '+', '.join(sorted({s for c in f['claim_ids'] for s in byclaim[c]['source_ids']}))+' |')
md+=['','## Claims','','| ID | Kind | Source and locator | Statement |','|---|---|---|---|']
for c in claims:
 loc=c.get('source_locator',str(c.get('locators','')));md.append('| '+c['id']+' | '+c['kind']+' | '+', '.join(c['source_ids'])+'; '+str(loc).replace('|','/')+' | '+c['statement'].replace('|','/')+' |')
(D/'GRAPH.md').write_text('\n'.join(md)+'\n')
# Footnotes make the report self-contained and link exact primary sources.
uids=['U01','U02','U04','U05','U06','U09','U10'];sids=['S01','S03','S04','S05','S06','S07'];dids=['D01','D02','D03','D04R','D05','D06','D07','D08','D09','D10','D11','D12','D13','D14'];order=uids+sids+dids;num={k:i+1 for i,k in enumerate(order)}
p=D/'REPORT.md';text=p.read_text()
repl={'[D11]':['D11'],'[D10, D14]':['D10','D14'],'[D01–D04R]':['D01','D02','D03','D04R'],'[S01, S07]':['S01','S07'],'[S03]':['S03'],'[D05]':['D05'],'[D08]':['D08'],'[S05]':['S05'],'[D06, D07]':['D06','D07'],'[S04, S06]':['S04','S06'],'[D12, D13]':['D12','D13']}
for old,keys in repl.items():text=text.replace(old,''.join('[^'+str(num[k])+']' for k in keys))
if '\n[^1]:' not in text:
 for sid in order:
  x=next(a for a in sources if a['id']==sid);authors=x.get('authors',x.get('publisher','Project documentation'));authors=', '.join(authors) if isinstance(authors,list) else authors;date=x.get('source_version',x.get('publication_date',x.get('publication_year','undated')));url=x.get('canonical_url',x.get('requested_url'));text+=f"\n[^{num[sid]}]: {authors}, [{x.get('title',sid)}]({url}), {date}. Capture {sid}; locators and limitations in the atlas/source index.\n"
p.write_text(text)
(D/'PAPER-ATLAS.md').write_text('# Annotated paper atlas\n\nThirteen complete primary academic documents, with related Elm thesis/paper counted as a shared lineage. The authors’ methods, formal claims and limitations were inspected at the named locators; no experiments or proofs were independently reproduced.\n\n'+(D/'usability-atlas.md').read_text().replace('# Empirical language usability atlas','## Empirical language usability atlas',1)+'\n'+(D/'semantics-atlas.md').read_text().replace('# Reactive semantics, effects and artifact identity','## Reactive semantics, effects and artifact identity',1))
idx=['# Source inventory','','Observation window: September 9, 2026 UTC. Thirteen complete academic documents; fourteen substantive official pages plus the failed static Elm shell. Full PDF files and text extracts are preserved. U06 is a complete publisher issue but only pp15–32 are the target paper. PDFs acquired do not mean every appendix proof was independently checked. No financial/user experiment was executed.','','| ID | Title | Original URL or local source | Capture / scope |','|---|---|---|---|']
for x in sources:
 url=x.get('canonical_url',x.get('requested_url',x.get('path','')));cap=x.get('raw_path',x.get('raw_file',x.get('local_path',x.get('path',''))));idx.append(f"| {x['id']} | {x.get('title','')} | {url} | `{cap}` |")
idx+=['','## Exact identity','','SHA-256, retrieval timestamps, requested/canonical URLs, access status, extraction hashes and version limitations are in [source-manifest.json](source-manifest.json). The four repository pins are in [repository-pins.json](repository-pins.json). These pins identify observed remote HEADs, not a full source audit.','','## Acquisition corrections and limitations','','D04 static HTML was a JavaScript shell; D04R retains the separately rendered Scrapling snapshot and readable article. D06–D10 initially selected a navigation article; `-body.txt` plus `-body.json` retain corrected last-article extraction without overwriting original files. D01 retry retains the first raw capture after an API-method mismatch; no earlier bytes were erased. Unison tutorial “unique by name” is qualified by the UUID-bearing reference D14. U01 is an author-formatted primary paper on a third-party public mirror, with weaker hosting provenance than an institutional copy. U04 is a technical report; final-publication byte identity is unverified. U10 captures observed arXiv v1 despite an unversioned endpoint. Failed U03/U07/U08 and S02 attempts remain excluded from read counts.','','No cookies, tokens or browser profiles were retained. Static/SSR pages used existing Scrapling 0.4.15; the one Elm SPA used the existing Chromium executable. Site-pattern lesson: select Unison’s final article, and verify extracted content, not merely HTTP200. No package installation or general scraping infrastructure was introduced.']
(D/'SOURCE-INDEX.md').write_text('\n'.join(idx)+'\n')
print('assembled',len(sources),'sources',len(claims),'claims',len(features),'features',len(edges),'edges')
